// Scenario tests. Each drives a tournament forward through several handler
// calls and asserts at structural milestones — the manual UI playthrough,
// automated. A failure on step 14 should be immediately apparent from the
// failed assertion's line number.

import { applyD1Migrations, env } from "cloudflare:test";
import { beforeAll, describe, expect, it } from "vitest";
import { expectErrorCode, expectOk } from "../../helpers/assertions";
import { makeTournament, makeUser } from "../../helpers/builders";
import { request } from "../../helpers/requests";

beforeAll(async () => {
	await applyD1Migrations(env.SHARE_DB, env.TEST_MIGRATIONS);
});

describe("tournament flow", () => {
	it("runs a 4-vs-4 swiss through a 1-round configuration, then completes the championship", async () => {
		// Arrange — 4 slots per division. Configure swiss to wrap in one round
		// so the championship has a small bracket: 2 advancers per division
		// → 4 championship slots → semifinal + final. Two admin gates: /start
		// and /transition-championship. Everything else advances automatically
		// as matches report.
		const t = await makeTournament({ slotsPerDivision: 4 });
		await expectOk(
			await request.patch({
				path: `/v1/tournaments/${t.tournamentId}`,
				as: t.admin,
				body: {
					swiss_wins_to_advance: 1,
					swiss_losses_to_eliminate: 1,
					swiss_max_rounds: 1,
				},
			}),
		);
		await expectOk(
			await request.post({
				path: `/v1/tournaments/${t.tournamentId}/start`,
				as: t.admin,
			}),
		);

		// Act — report Swiss Round 1 results (slot_a always wins).
		const swissMatches = await t.matches();
		for (const m of swissMatches) {
			if (m.status === "bye") continue;
			await expectOk(
				await request.patch({
					path: `/v1/tournaments/${t.tournamentId}/matches/${m.match_id}`,
					as: t.admin,
					body: { winner_slot_id: m.slot_a_id, status: "complete" },
				}),
			);
		}

		// Transition to championship. With 2-each advancers across A/B and
		// clean ranks (no ties), no override is needed.
		await expectOk(
			await request.post({
				path: `/v1/tournaments/${t.tournamentId}/transition-championship`,
				as: t.admin,
			}),
		);
		expect((await t.refresh()).status).toBe("championship");

		// Championship round 1 (semifinals) was generated by transition
		// already in_progress. Report both matches; auto-advance spawns R2.
		const champR1 = (await t.rounds()).find(
			(r) => r.phase === "championship" && r.round_number === 1,
		)!;
		expect(champR1.status).toBe("in_progress");
		const semis = (await t.matches()).filter(
			(m) => m.round_id === champR1.round_id,
		);
		for (const m of semis) {
			await expectOk(
				await request.patch({
					path: `/v1/tournaments/${t.tournamentId}/matches/${m.match_id}`,
					as: t.admin,
					body: { winner_slot_id: m.slot_a_id, status: "complete" },
				}),
			);
		}

		// The final spawned automatically. Report it → tournament completes.
		const champR2 = (await t.rounds()).find(
			(r) => r.phase === "championship" && r.round_number === 2,
		)!;
		const finals = (await t.matches()).filter(
			(m) => m.round_id === champR2.round_id,
		);
		expect(finals).toHaveLength(1);
		await expectOk(
			await request.patch({
				path: `/v1/tournaments/${t.tournamentId}/matches/${finals[0].match_id}`,
				as: t.admin,
				body: { winner_slot_id: finals[0].slot_a_id, status: "complete" },
			}),
		);

		// Assert — terminal status reached (auto-completed), every match
		// has a winner.
		expect((await t.refresh()).status).toBe("complete");
		const finalMatches = await t.matches();
		for (const m of finalMatches) {
			expect(m.winner_slot_id).not.toBeNull();
		}
	});

	it("handles a 3-vs-3 swiss tournament with byes in round 1", async () => {
		// Arrange — odd slot count → one bye per division per round.
		const t = await makeTournament({
			slotsPerDivision: 3,
			advanceTo: "swiss-round-1-generated",
		});

		// Assert — each division has exactly one bye match.
		const matches = await t.matches();
		const byesA = matches.filter(
			(m) =>
				m.status === "bye" &&
				t.slotsByDivision.A.some((s) => s.slotId === m.slot_a_id),
		);
		const byesB = matches.filter(
			(m) =>
				m.status === "bye" &&
				t.slotsByDivision.B.some((s) => s.slotId === m.slot_a_id),
		);
		expect(byesA).toHaveLength(1);
		expect(byesB).toHaveLength(1);
		// Bye matches have slot_b_id = null and winner = slot_a.
		for (const bye of [...byesA, ...byesB]) {
			expect(bye.slot_b_id).toBeNull();
			expect(bye.winner_slot_id).toBe(bye.slot_a_id);
		}
	});

	it("rejects /start when swiss_advance_count exceeds the smaller division's size (#9)", async () => {
		// Override swiss_advance_count to 5 while only 4 slots per division
		// exist. /start must reject up-front rather than letting the
		// tournament run to completion and then fail at transition.
		const t = await makeTournament({ slotsPerDivision: 4 });
		await expectOk(
			await request.patch({
				path: `/v1/tournaments/${t.tournamentId}`,
				as: t.admin,
				body: { swiss_advance_count: 5 },
			}),
		);

		const res = await request.post({
			path: `/v1/tournaments/${t.tournamentId}/start`,
			as: t.admin,
		});

		await expectErrorCode(res, {
			status: 409,
			code: "ADVANCE_COUNT_TOO_LARGE",
		});
	});

	it("returns the caller's pending matches across multiple tournaments via /v1/users/me/matches", async () => {
		// Arrange — same user owns a slot in two separate tournaments. (A
		// single user can't own multiple slots in one tournament — slot
		// discord_username is unique per bulk-create batch.)
		const player = await makeUser({ discordUsername: "alice-test" });
		const t1 = await makeTournament({
			slotsPerDivision: 4,
			slotOwners: { A: [player] },
			advanceTo: "swiss-round-1-generated",
		});
		const t2 = await makeTournament({
			slotsPerDivision: 4,
			slotOwners: { A: [player] },
			advanceTo: "swiss-round-1-generated",
		});

		// Act
		const res = await request.get({
			path: "/v1/users/me/matches",
			as: player,
		});
		const body = await expectOk<{ matches: Array<Record<string, unknown>> }>(
			res,
		);

		// Assert — one match per tournament, both pending. Tournament context
		// is denormalized into each row.
		expect(body.matches).toHaveLength(2);
		const tournamentIds = new Set(body.matches.map((m) => m.tournament_id));
		expect(tournamentIds).toEqual(new Set([t1.tournamentId, t2.tournamentId]));
		for (const m of body.matches) {
			expect(m.status).toBe("pending");
		}
	});
});
