// Auto-advance + match_index tests. With the manual lifecycle gates
// collapsed, round generation now happens implicitly: Round 1 spawns
// from POST /start, and Round N+1 spawns automatically when Round N's
// last pending match is reported. Championship works the same way after
// the (still manual) /transition-championship gate.

import { applyD1Migrations, env } from "cloudflare:test";
import { beforeAll, describe, expect, it } from "vitest";
import { expectOk } from "../../helpers/assertions";
import { makeTournament } from "../../helpers/builders";
import { request } from "../../helpers/requests";

beforeAll(async () => {
	await applyD1Migrations(env.SHARE_DB, env.TEST_MIGRATIONS);
});

describe("match_index population (#3)", () => {
	it("populates match_index 1..N for Round 1 of each division (from /start)", async () => {
		const t = await makeTournament({ advanceTo: "swiss-round-1-generated" });

		const matches = await t.matches();
		expect(matches.length).toBeGreaterThan(0);
		const byRound = new Map<string, number[]>();
		for (const m of matches) {
			expect(m.match_index).not.toBeNull();
			const list = byRound.get(m.round_id) ?? [];
			list.push(m.match_index!);
			byRound.set(m.round_id, list);
		}
		for (const [, indexes] of byRound) {
			indexes.sort((a, b) => a - b);
			expect(indexes).toEqual(
				Array.from({ length: indexes.length }, (_, i) => i + 1),
			);
		}
	});

	it("populates match_index 1..N when championship round 1 is generated by /transition-championship", async () => {
		const t = await makeTournament({ slotsPerDivision: 4 });
		await expectOk(
			await request.patch({
				path: `/v1/tournaments/${t.tournamentId}`,
				as: t.admin,
				body: {
					swiss_wins_to_advance: 1,
					swiss_losses_to_eliminate: 1,
					swiss_max_rounds: 1,
				},
			}),
		);
		await expectOk(
			await request.post({
				path: `/v1/tournaments/${t.tournamentId}/start`,
				as: t.admin,
			}),
		);
		// Report Round 1; auto-advance won't generate Round 2 since
		// swiss_max_rounds=1.
		for (const m of await t.matches()) {
			if (m.status === "bye") continue;
			await expectOk(
				await request.patch({
					path: `/v1/tournaments/${t.tournamentId}/matches/${m.match_id}`,
					as: t.admin,
					body: { winner_slot_id: m.slot_a_id, status: "reported" },
				}),
			);
		}
		await expectOk(
			await request.post({
				path: `/v1/tournaments/${t.tournamentId}/transition-championship`,
				as: t.admin,
			}),
		);

		const champRounds = (await t.rounds()).filter(
			(r) => r.phase === "championship",
		);
		expect(champRounds).toHaveLength(1);
		const champMatches = (await t.matches()).filter(
			(m) => m.round_id === champRounds[0].round_id,
		);
		expect(champMatches.length).toBeGreaterThan(0);
		const indexes = champMatches.map((m) => m.match_index).sort();
		expect(indexes).toEqual(
			Array.from({ length: indexes.length }, (_, i) => i + 1),
		);
	});

	it("populates match_index 1..N on a championship follow-up round (auto-generated)", async () => {
		const t = await makeTournament({ slotsPerDivision: 4 });
		await expectOk(
			await request.patch({
				path: `/v1/tournaments/${t.tournamentId}`,
				as: t.admin,
				body: {
					swiss_wins_to_advance: 1,
					swiss_losses_to_eliminate: 1,
					swiss_max_rounds: 1,
				},
			}),
		);
		await expectOk(
			await request.post({
				path: `/v1/tournaments/${t.tournamentId}/start`,
				as: t.admin,
			}),
		);
		for (const m of await t.matches()) {
			if (m.status === "bye") continue;
			await expectOk(
				await request.patch({
					path: `/v1/tournaments/${t.tournamentId}/matches/${m.match_id}`,
					as: t.admin,
					body: { winner_slot_id: m.slot_a_id, status: "reported" },
				}),
			);
		}
		await expectOk(
			await request.post({
				path: `/v1/tournaments/${t.tournamentId}/transition-championship`,
				as: t.admin,
			}),
		);

		// Report championship R1; auto-advance should spawn R2 (the final).
		const champR1 = (await t.rounds()).find(
			(r) => r.phase === "championship" && r.round_number === 1,
		)!;
		for (const m of await t.matches()) {
			if (m.round_id !== champR1.round_id) continue;
			await expectOk(
				await request.patch({
					path: `/v1/tournaments/${t.tournamentId}/matches/${m.match_id}`,
					as: t.admin,
					body: { winner_slot_id: m.slot_a_id, status: "reported" },
				}),
			);
		}

		const champR2 = (await t.rounds()).find(
			(r) => r.phase === "championship" && r.round_number === 2,
		);
		expect(champR2).toBeDefined();
		const r2Matches = (await t.matches()).filter(
			(m) => m.round_id === champR2!.round_id,
		);
		expect(r2Matches.length).toBeGreaterThan(0);
		for (const m of r2Matches) {
			expect(m.match_index).not.toBeNull();
		}
		const indexes = r2Matches.map((m) => m.match_index).sort();
		expect(indexes).toEqual(
			Array.from({ length: indexes.length }, (_, i) => i + 1),
		);
	});
});

describe("ordering via public read paths (#3)", () => {
	it("GET /v1/tournaments/:id/matches returns matches in match_index order within each round", async () => {
		const t = await makeTournament({ advanceTo: "swiss-round-1-generated" });

		const res = await request.get({
			path: `/v1/tournaments/${t.tournamentId}/matches`,
			as: t.admin,
		});
		const body = await expectOk<{
			matches: Array<{
				match_id: string;
				round_id: string;
				match_index: number | null;
			}>;
		}>(res);

		const byRound = new Map<string, Array<{ match_index: number | null }>>();
		for (const m of body.matches) {
			const list = byRound.get(m.round_id) ?? [];
			list.push(m);
			byRound.set(m.round_id, list);
		}
		for (const [, list] of byRound) {
			const indexes = list.map((m) => m.match_index);
			expect(indexes).toEqual([...indexes].sort());
		}
	});

	it("produces identical match ordering across two reads of the same DB state", async () => {
		const t = await makeTournament({ advanceTo: "swiss-round-1-generated" });

		const [first, second] = await Promise.all([
			request.get({
				path: `/v1/tournaments/${t.tournamentId}/matches`,
				as: t.admin,
			}),
			request.get({
				path: `/v1/tournaments/${t.tournamentId}/matches`,
				as: t.admin,
			}),
		]);
		const a = await expectOk<{ matches: Array<{ match_id: string }> }>(first);
		const b = await expectOk<{ matches: Array<{ match_id: string }> }>(second);

		expect(a.matches.map((m) => m.match_id)).toEqual(
			b.matches.map((m) => m.match_id),
		);
	});
});

describe("auto-advance", () => {
	it("does not generate Round 2 while Round 1 still has pending matches in a division", async () => {
		const t = await makeTournament({
			slotsPerDivision: 4,
			advanceTo: "swiss-round-1-generated",
		});
		// Filter Div A's matches by checking slot_a_id against the division's
		// slots (the match row doesn't denormalize division).
		const divASlotIds = new Set(t.slotsByDivision.A.map((s) => s.slotId));
		const divAMatches = (await t.matches()).filter(
			(m) => m.status === "pending" && divASlotIds.has(m.slot_a_id),
		);
		// Leave the very last Div A pending match unreported.
		for (const m of divAMatches.slice(0, -1)) {
			await expectOk(
				await request.patch({
					path: `/v1/tournaments/${t.tournamentId}/matches/${m.match_id}`,
					as: t.admin,
					body: { winner_slot_id: m.slot_a_id, status: "reported" },
				}),
			);
		}
		// Div A still has only Round 1 (Round 2 hasn't spawned). Div B
		// status independent.
		const rounds = await t.rounds();
		const divARounds = rounds.filter(
			(r) => r.phase === "swiss" && r.division === "A",
		);
		expect(divARounds).toHaveLength(1);
		expect(divARounds[0].round_number).toBe(1);
	});

	it("auto-generates the next Swiss round in a division when its last match reports", async () => {
		const t = await makeTournament({
			slotsPerDivision: 4,
			advanceTo: "swiss-round-1-reported",
		});
		// Builder reported every Round 1 match. Auto-advance should have
		// generated Round 2 for both divisions, all in_progress.
		const rounds = await t.rounds();
		const r1 = rounds.filter(
			(r) => r.phase === "swiss" && r.round_number === 1,
		);
		const r2 = rounds.filter(
			(r) => r.phase === "swiss" && r.round_number === 2,
		);
		expect(r1).toHaveLength(2);
		expect(r2).toHaveLength(2);
		expect(r1.every((r) => r.status === "complete")).toBe(true);
		expect(r2.every((r) => r.status === "in_progress")).toBe(true);
		expect(r2.every((r) => r.started_at !== null)).toBe(true);
	});

	it("stops auto-generating Swiss rounds at swiss_max_rounds", async () => {
		const t = await makeTournament({ slotsPerDivision: 4 });
		await expectOk(
			await request.patch({
				path: `/v1/tournaments/${t.tournamentId}`,
				as: t.admin,
				body: { swiss_max_rounds: 1 },
			}),
		);
		await expectOk(
			await request.post({
				path: `/v1/tournaments/${t.tournamentId}/start`,
				as: t.admin,
			}),
		);
		for (const m of await t.matches()) {
			if (m.status === "bye") continue;
			await expectOk(
				await request.patch({
					path: `/v1/tournaments/${t.tournamentId}/matches/${m.match_id}`,
					as: t.admin,
					body: { winner_slot_id: m.slot_a_id, status: "reported" },
				}),
			);
		}
		const rounds = await t.rounds();
		expect(rounds.filter((r) => r.phase === "swiss")).toHaveLength(2);
		// Tournament stays in swiss (no auto-transition to championship);
		// admin will press the transition button.
		const tournamentRow = await t.refresh();
		expect(tournamentRow.status).toBe("swiss");
	});

	it("auto-completes the tournament when the championship final is reported", async () => {
		const t = await makeTournament({ slotsPerDivision: 4 });
		await expectOk(
			await request.patch({
				path: `/v1/tournaments/${t.tournamentId}`,
				as: t.admin,
				body: {
					swiss_wins_to_advance: 1,
					swiss_losses_to_eliminate: 1,
					swiss_max_rounds: 1,
				},
			}),
		);
		await expectOk(
			await request.post({
				path: `/v1/tournaments/${t.tournamentId}/start`,
				as: t.admin,
			}),
		);
		for (const m of await t.matches()) {
			if (m.status === "bye") continue;
			await expectOk(
				await request.patch({
					path: `/v1/tournaments/${t.tournamentId}/matches/${m.match_id}`,
					as: t.admin,
					body: { winner_slot_id: m.slot_a_id, status: "reported" },
				}),
			);
		}
		await expectOk(
			await request.post({
				path: `/v1/tournaments/${t.tournamentId}/transition-championship`,
				as: t.admin,
			}),
		);
		// Play championship R1 (semis) → auto-generates R2 (final).
		const champR1 = (await t.rounds()).find(
			(r) => r.phase === "championship" && r.round_number === 1,
		)!;
		for (const m of (await t.matches()).filter(
			(m) => m.round_id === champR1.round_id,
		)) {
			await expectOk(
				await request.patch({
					path: `/v1/tournaments/${t.tournamentId}/matches/${m.match_id}`,
					as: t.admin,
					body: { winner_slot_id: m.slot_a_id, status: "reported" },
				}),
			);
		}
		// Report the final → auto-completes.
		const champR2 = (await t.rounds()).find(
			(r) => r.phase === "championship" && r.round_number === 2,
		)!;
		const finalMatch = (await t.matches()).find(
			(m) => m.round_id === champR2.round_id,
		)!;
		await expectOk(
			await request.patch({
				path: `/v1/tournaments/${t.tournamentId}/matches/${finalMatch.match_id}`,
				as: t.admin,
				body: { winner_slot_id: finalMatch.slot_a_id, status: "reported" },
			}),
		);
		const tournamentRow = await t.refresh();
		expect(tournamentRow.status).toBe("complete");
	});
});
