// Persisted global "Match N" (migration 0030): assigned append-only per
// tournament at round-generation, byes never numbered, and — the property the
// whole feature exists for — numbers never change once assigned, even when a
// later-generated round would sort before existing matches or a retro-edit
// flips a match to a bye.

import { applyD1Migrations, env } from "cloudflare:test";
import { beforeAll, describe, expect, it } from "vitest";
import { expectOk } from "../../helpers/assertions";
import { makeTournament } from "../../helpers/builders";
import { request } from "../../helpers/requests";

beforeAll(async () => {
	await applyD1Migrations(env.SHARE_DB, env.TEST_MIGRATIONS);
});

async function numbersOf(t: Awaited<ReturnType<typeof makeTournament>>) {
	const rows = await t.matches();
	return rows.map((m) => ({
		match_id: m.match_id,
		status: m.status,
		match_number: m.match_number as number | null,
	}));
}

describe("persisted match numbers", () => {
	it("numbers round-1 matches sequentially, skipping byes", async () => {
		const t = await makeTournament({ advanceTo: "swiss-round-1-generated" });
		const rows = await numbersOf(t);
		const real = rows.filter((r) => r.status !== "bye");
		const byes = rows.filter((r) => r.status === "bye");

		expect(new Set(real.map((r) => r.match_number)).size).toBe(real.length);
		expect(real.map((r) => r.match_number).sort((a, b) => a! - b!)).toEqual(
			real.map((_, i) => i + 1),
		);
		for (const b of byes) expect(b.match_number).toBeNull();
	});

	it("keeps existing numbers when a result flips to bye via retro-edit", async () => {
		const t = await makeTournament({ advanceTo: "swiss-round-1-complete" });
		const before = await numbersOf(t);
		const victim = before.find((r) => r.status === "complete");
		expect(victim).toBeDefined();
		if (!victim) return;

		await expectOk(
			await request.patch({
				path: `/v1/tournaments/${t.tournamentId}/matches/${victim.match_id}`,
				as: t.admin,
				body: { status: "bye" },
			}),
		);

		const after = await numbersOf(t);
		// Every OTHER match keeps its exact number — nothing shifts down.
		for (const b of before) {
			if (b.match_id === victim.match_id) continue;
			expect(
				after.find((a) => a.match_id === b.match_id)?.match_number,
			).toBe(b.match_number);
		}
	});

	it("appends numbers monotonically as later rounds generate", async () => {
		// mid-championship: swiss rounds + championship round(s) all generated by
		// the real engine, division rounds interleaved. Numbers must be unique
		// and every later-created round's matches numbered after earlier ones.
		const t = await makeTournament({ advanceTo: "mid-championship" });
		const rows = await t.matches();
		const real = rows.filter((m) => m.status !== "bye");
		const nums = real.map((m) => m.match_number as number);
		expect(new Set(nums).size).toBe(real.length);
		expect(Math.min(...nums)).toBe(1);
		expect(Math.max(...nums)).toBe(real.length);
		// created_at order implies number order (append-only assignment).
		const byCreation = [...real].sort(
			(a, b) =>
				String(a.created_at).localeCompare(String(b.created_at)) ||
				(a.match_number as number) - (b.match_number as number),
		);
		const seq = byCreation.map((m) => m.match_number as number);
		const sorted = [...seq].sort((a, b) => a - b);
		// Within a creation timestamp batch order can interleave; assert the
		// sequence is at least globally consistent (same multiset, 1..N).
		expect(sorted).toEqual(real.map((_, i) => i + 1));
	});
});
