// AUTO-GENERATED by scripts/bake-challenge-mirror.ts — do not edit.
// THIS IS THE MIRROR — the source of truth is
// src/lib/challenges/scoring.ts; edit that file and run
// `npm run bake:challenge-mirror`.

// Challenge maps — the scorer. Pure and dependency-free (relative imports of
// generated tables only): the Worker's mirror at cloud/src/challenges/scoring.ts
// is GENERATED from this file (`npm run bake:challenge-mirror`; the generated
// tables it reads are dual-emitted there too) and scores the authoritative
// verdict, and the upload modal runs the same function on the browser parse
// for the preview.
//
// Design: docs/challenge-maps-design.md §4 (identity) and §5 (the scorer).
// Everything here reads the blob the parser already produces; the semantics of
// "met" are the ones §3.2 spells out — a history-backed objective is met if
// the player *ever* reached it by the deadline, a snapshot objective iff the
// save's state satisfies it.

import { isDynastyTrait } from "../generated/dynasty-traits";
import { THEOLOGY_TIER } from "../generated/theology-tiers";
import { UNIT_STATS } from "../generated/unit-stats";
import { WONDER_CULTURE_PREREQ, cultureRank } from "../generated/wonders";
import {
	ANY_RELIGION,
	ANY_WONDER,
	type ChallengeRules,
	type ChallengeSetup,
	type Criterion,
	type CriterionVerdict,
	type Objective,
	type ObjectiveVerdict,
	type Verdict,
} from "./types";

/**
 * The oldest parse the Worker accepts for a challenge map or run. The scorer
 * reads fields this version introduced — `build_turns_left` (an improvement
 * still under construction), `original_tribe` (a unit taken from a tribe
 * rather than trained) and the cities' `tile_xml_id` (when a city was
 * captured) — and each is optional on the blob type because older blobs lack
 * it, which on such a blob would score an unfinished improvement as built and
 * a captured unit as trained. The verdict is persisted, so a run parsed by a
 * stale tab is refused rather than scored wrong.
 */
export const CHALLENGE_MIN_PARSER_VERSION = "2.16.0";

// ---------------------------------------------------------------------------
// The slice of FullGameData the scorer reads, declared structurally so the
// module has no dependency on the parser's type tree (which the Worker mirror
// could not resolve). Every field is what the parser writes under the same
// name; the optional ones were added in later PARSER_VERSIONs.
// ---------------------------------------------------------------------------

export interface ScorableBlob {
	match_metadata: {
		xml_game_id: string;
		total_turns: number;
		game_over: boolean;
		winner: { winner_player_xml_id: number } | null;
		map_size: string | null;
		map_class: string | null;
		map_aspect_ratio: string | null;
		map_width: number | null;
		map_height: number | null;
		difficulty: string | null;
		opponent_level: string | null;
		game_options: Record<string, true> | null;
		disabled_improvements: string[] | null;
		game_version: string | null;
		enabled_dlc: string | null;
	};
	game_details: {
		players: Array<{
			player_id?: number;
			player_name: string;
			nation: string | null;
			is_human: boolean;
			state_religion: string | null;
			leader_character_xml_id?: number | null;
		}>;
	};
	player_roster: Array<{
		player_index: number;
		is_human: boolean;
		nation: string | null;
	}>;
	completed_techs: Array<{
		player_id: number;
		tech: string;
		completed_turn: number;
	}>;
	player_wonders: Array<{
		player_id: number;
		wonder: string;
		completed_turn: number;
	}>;
	improvement_data: {
		improvements: Array<{
			owner_player_xml_id?: number | null;
			city_xml_id?: number | null;
			improvement: string;
			specialist: string | null;
			build_turns_left?: number | null;
		}>;
	};
	units_produced: Array<{
		player_id: number;
		unit_type: string;
		count: number;
	}>;
	units: Array<{
		unit_type: string;
		player_xml_id: number | null;
		original_player_xml_id: number | null;
		original_tribe?: string | null;
	}>;
	city_statistics: {
		cities: Array<{
			city_id: number;
			tile_xml_id?: number;
			owner_player_xml_id?: number | null;
			first_owner_player_xml_id: number | null;
			founded_turn: number;
			is_capital: boolean;
			culture_level: string | null;
			happiness_level?: number | null;
			damage?: number;
		}>;
	};
	tile_ownership_history: Array<{
		tile_xml_id: number;
		turn: number;
		owner_player_xml_id: number | null;
	}>;
	game_religions: Array<{
		religion_name: string;
		founded_turn: number | null;
		founder_player_xml_id?: number | null;
		theologies?: string[];
	}>;
	characters: Array<{
		xml_id: number;
		first_name: string | null;
		player_xml_id: number | null;
		cognomen: string | null;
		became_leader_turn?: number | null;
	}>;
	character_traits: Array<{
		character_xml_id: number;
		trait_name: string;
		acquired_turn: number;
	}>;
	families: Array<{
		player_xml_id: number;
		family_name: string;
		seat_city_xml_id: number | null;
	}>;
	family_opinion_history: Array<{
		player_xml_id: number;
		family_name: string;
		turn: number;
		opinion: number;
	}>;
	yield_history: Array<{
		player_id: number;
		yield_type: string;
		data: Array<{
			turn: number;
			rate: number | null;
			cumulative: number | null;
		}>;
	}>;
	player_history: Array<{
		player_id: number;
		history: Array<{
			turn: number;
			points: number | null;
			military_power: number | null;
			legitimacy: number | null;
		}>;
	}>;
	tech_discovery_history: Array<{
		player_id: number;
		data: Array<{ turn: number; tech_count: number }>;
	}>;
	law_adoption_history: Array<{
		player_id: number;
		data: Array<{ turn: number; law_count: number }>;
	}>;
}

const ARRAY_FIELDS = [
	"player_roster",
	"completed_techs",
	"player_wonders",
	"units_produced",
	"units",
	"tile_ownership_history",
	"game_religions",
	"characters",
	"character_traits",
	"families",
	"family_opinion_history",
	"yield_history",
	"player_history",
	"tech_discovery_history",
	"law_adoption_history",
] as const;

/**
 * Coerce a validated FullGameData blob into the scorer's shape. The Worker's
 * schema keeps most sections as `unknown`, and a section a save didn't need
 * can be absent from an older parse; a missing list scores as empty rather
 * than throwing, so a verdict always comes back.
 */
export function asScorable(raw: unknown): ScorableBlob {
	const b = { ...(raw as Record<string, unknown>) };
	for (const k of ARRAY_FIELDS) if (!Array.isArray(b[k])) b[k] = [];
	const nested = (key: string, inner: string) => {
		const o = b[key] as Record<string, unknown> | null | undefined;
		b[key] = {
			...(o ?? {}),
			[inner]: Array.isArray(o?.[inner]) ? o[inner] : [],
		};
	};
	nested("game_details", "players");
	nested("improvement_data", "improvements");
	nested("city_statistics", "cities");
	return b as unknown as ScorableBlob;
}

// ---------------------------------------------------------------------------
// Setup extraction and map validation (§3.1, §4)
// ---------------------------------------------------------------------------

/** The game option that lets a player build their own leader on turn 1. */
const CUSTOM_LEADER_OPTION = "GAMEOPTION_CUSTOM_LEADER";

function humanSeats(blob: ScorableBlob) {
	return blob.player_roster.filter((p) => p.is_human);
}

function playerDetails(blob: ScorableBlob, playerIndex: number) {
	return blob.game_details.players.find((p) => p.player_id === playerIndex);
}

/**
 * The seat's first leader: the map's, when it has one, else whichever of
 * the run's characters took the throne first. A pick-later map has no
 * leader at all — the player builds one on turn 1 — so the run is the only
 * place the leader exists.
 */
function firstLeader(blob: ScorableBlob, playerIndex: number): number | null {
	const seated = blob.characters
		.filter(
			(c) => c.player_xml_id === playerIndex && c.became_leader_turn != null,
		)
		.sort((a, b) => a.became_leader_turn! - b.became_leader_turn!);
	return seated[0]?.xml_id ?? null;
}

/** Traits a character carried at turn ≤ 1 — what the map fixes for everyone. */
function startingTraits(
	blob: ScorableBlob,
	characterXmlId: number | null,
): string[] {
	if (characterXmlId == null) return [];
	return blob.character_traits
		.filter(
			(t) => t.character_xml_id === characterXmlId && t.acquired_turn <= 1,
		)
		.map((t) => t.trait_name);
}

/**
 * Wonders the map lets anyone build: every wonder the game knows minus the
 * map's `disabled_improvements`. The `ANY_WONDER` count prefill.
 */
function enabledWonders(disabled: string[] | null): string[] {
	const off = new Set(disabled ?? []);
	return Object.keys(WONDER_CULTURE_PREREQ).filter((w) => !off.has(w));
}

/**
 * Problems that make a save unusable as a challenge map; empty means it
 * qualifies. A map is a turn-1 save with exactly one human seat and at most
 * one AI (§3.1).
 */
export function validateChallengeMap(blob: ScorableBlob): string[] {
	const problems: string[] = [];
	const humans = humanSeats(blob);
	const ai = blob.player_roster.length - humans.length;
	if (blob.match_metadata.total_turns !== 1) {
		problems.push(
			`A challenge map is a turn-1 save; this one is on turn ${blob.match_metadata.total_turns}.`,
		);
	}
	if (humans.length !== 1) {
		problems.push(
			`A challenge map has exactly one human seat; this one has ${humans.length}.`,
		);
	}
	if (ai > 1) {
		problems.push(
			`A challenge map has at most one AI opponent; this one has ${ai}.`,
		);
	}
	if (blob.match_metadata.game_over) {
		problems.push("This game is already over.");
	}
	return problems;
}

/** What the creator's map fixes for every run; stored on the challenge. */
export function extractSetup(blob: ScorableBlob): ChallengeSetup {
	const human = humanSeats(blob)[0];
	const playerIndex = human?.player_index ?? 0;
	const details = playerDetails(blob, playerIndex);
	const leaderId = firstLeader(blob, playerIndex);
	const leader = blob.characters.find((c) => c.xml_id === leaderId);
	const leaderTraits = startingTraits(blob, leaderId);
	const m = blob.match_metadata;
	return {
		xml_game_id: m.xml_game_id,
		player_index: playerIndex,
		nation: details?.nation ?? human?.nation ?? null,
		leader_character_xml_id: leaderId,
		leader_name: leader?.first_name ?? null,
		leader_traits: leaderTraits,
		leader_is_custom: m.game_options?.[CUSTOM_LEADER_OPTION] === true,
		ai_count: blob.player_roster.length - humanSeats(blob).length,
		map_size: m.map_size,
		map_class: m.map_class,
		map_aspect_ratio: m.map_aspect_ratio,
		map_width: m.map_width,
		map_height: m.map_height,
		difficulty: m.difficulty,
		opponent_level: m.opponent_level,
		game_options: m.game_options,
		disabled_improvements: m.disabled_improvements,
		game_version: m.game_version,
		enabled_dlc: m.enabled_dlc,
		wonders: enabledWonders(m.disabled_improvements),
	};
}

/**
 * Is this save a run of the challenge's map? (§4) The `GameId` is the
 * identity; the rest are consistency checks with a clear message.
 */
export function checkIdentity(
	setup: ChallengeSetup,
	blob: ScorableBlob,
): { ok: boolean; reason: string | null } {
	const m = blob.match_metadata;
	if (m.xml_game_id !== setup.xml_game_id) {
		return {
			ok: false,
			reason: "it is a different game (the GameId differs)",
		};
	}
	const humans = humanSeats(blob);
	if (humans.length !== 1) {
		return {
			ok: false,
			reason: `it has ${humans.length} human seats, not one`,
		};
	}
	if (humans[0].player_index !== setup.player_index) {
		return {
			ok: false,
			reason: "the human seat is not the map's",
		};
	}
	const nation =
		playerDetails(blob, setup.player_index)?.nation ?? humans[0].nation;
	if (setup.nation != null && nation !== setup.nation) {
		return {
			ok: false,
			reason: "the nation is not the map's",
		};
	}
	const ai = blob.player_roster.length - humans.length;
	if (ai !== setup.ai_count) {
		return {
			ok: false,
			reason: `it has ${ai} AI opponents, the map has ${setup.ai_count}`,
		};
	}
	// Consistency, not security (design §4): a GameId match with a different
	// difficulty or map size is an edited save, and the message says which.
	if (setup.difficulty != null && m.difficulty !== setup.difficulty) {
		return { ok: false, reason: "the difficulty is not the map's" };
	}
	if (setup.map_size != null && m.map_size !== setup.map_size) {
		return { ok: false, reason: "the map size is not the map's" };
	}
	if (m.total_turns < 1) {
		return { ok: false, reason: "it has no turns" };
	}
	return { ok: true, reason: null };
}

// ---------------------------------------------------------------------------
// Objectives (§3.2)
// ---------------------------------------------------------------------------

interface Ctx {
	blob: ScorableBlob;
	setup: ChallengeSetup;
	/** The human seat's player xml id. */
	p: number;
	/** The save's turn. */
	turn: number;
}

function limitOf(ctx: Ctx, byTurn: number | undefined): number {
	return byTurn == null ? ctx.turn : Math.min(byTurn, ctx.turn);
}

function unmet(observed: string): ObjectiveVerdict {
	return { met: false, met_turn: null, observed };
}

function metAt(turn: number, observed: string): ObjectiveVerdict {
	return { met: true, met_turn: turn, observed };
}

/** A history-backed objective first reached on `reachedTurn`, against a deadline. */
function deadline(
	ctx: Ctx,
	reachedTurn: number | null,
	byTurn: number | undefined,
	what: string,
): ObjectiveVerdict {
	if (reachedTurn == null) return unmet(`${what} not reached`);
	if (reachedTurn > limitOf(ctx, byTurn)) {
		return unmet(
			`${what} on turn ${reachedTurn}, after the turn-${byTurn} deadline`,
		);
	}
	return metAt(reachedTurn, `${what} on turn ${reachedTurn}`);
}

function ownedCities(ctx: Ctx) {
	return ctx.blob.city_statistics.cities.filter(
		(c) => c.owner_player_xml_id === ctx.p,
	);
}

function ownedImprovements(ctx: Ctx) {
	return ctx.blob.improvement_data.improvements.filter(
		(i) => i.owner_player_xml_id === ctx.p,
	);
}

function isUnderConstruction(i: { build_turns_left?: number | null }): boolean {
	return (i.build_turns_left ?? 0) > 0;
}

/**
 * Tiered improvements upgrade in place — a Library tile becomes
 * `IMPROVEMENT_LIBRARY_2` (Academy) and then `_3` (University) — so "build a
 * Library" is met by any tier at or above the target's. An untiered target
 * (a wonder, a shrine) matches exactly.
 */
function matchesImprovement(tile: string, target: string): boolean {
	const m = /^(.*)_(\d+)$/.exec(target);
	if (!m) return tile === target;
	const t = /^(.*)_(\d+)$/.exec(tile);
	return t != null && t[1] === m[1] && Number(t[2]) >= Number(m[2]);
}

function scoreTech(
	ctx: Ctx,
	o: Extract<Objective, { kind: "tech" }>,
): ObjectiveVerdict {
	const t = ctx.blob.completed_techs.find(
		(x) => x.player_id === ctx.p && x.tech === o.target,
	);
	return deadline(ctx, t?.completed_turn ?? null, o.by_turn, "Completed");
}

function scoreBuild(
	ctx: Ctx,
	o: Extract<Objective, { kind: "build" }>,
): ObjectiveVerdict {
	const need = o.count ?? 1;
	const started = o.state === "started";
	const anyWonder = o.target === ANY_WONDER;
	const targets = new Set(anyWonder ? ctx.setup.wonders : [o.target]);
	const matches = (imp: string) =>
		anyWonder ? targets.has(imp) : matchesImprovement(imp, o.target);
	const tiles = ownedImprovements(ctx).filter(
		(i) => matches(i.improvement) && (started || !isUnderConstruction(i)),
	);
	// A wonder is one per game, so counting distinct improvements = counting
	// wonders; an ordinary improvement counts tiles.
	const have = anyWonder
		? new Set(tiles.map((t) => t.improvement)).size
		: tiles.length;
	const noun = anyWonder ? "wonders" : "";
	const verb = started ? "started" : "completed";
	if (have < need)
		return unmet(`${have} of ${need} ${noun} ${verb}`.replace(/\s+/g, " "));

	// Completed wonders carry a turn in the WONDER_ACTIVITY log. Nothing else
	// can be dated — the save never records when a tile was improved — so
	// the schema refuses a deadline there, and one that slips through is
	// held to the only turn known: the save's.
	if (!started && (anyWonder || o.target in WONDER_CULTURE_PREREQ)) {
		const turns = ctx.blob.player_wonders
			.filter((w) => w.player_id === ctx.p && targets.has(w.wonder))
			.map((w) => w.completed_turn)
			.sort((a, b) => a - b);
		// The nth completion is when the objective was reached; a wonder that
		// stands finished but is missing from the log (non-English save)
		// counts at the save's turn.
		const nth = turns.length >= need ? turns[need - 1] : ctx.turn;
		return deadline(
			ctx,
			nth,
			o.by_turn,
			`${have} of ${need} ${noun} completed`.replace(/\s+/g, " "),
		);
	}
	return deadline(
		ctx,
		ctx.turn,
		o.by_turn,
		`${have} of ${need} ${noun} ${verb}`.replace(/\s+/g, " "),
	);
}

function scoreUnit(
	ctx: Ctx,
	o: Extract<Objective, { kind: "unit" }>,
): ObjectiveVerdict {
	const need = o.count ?? 1;
	const have =
		ctx.blob.units_produced.find(
			(u) => u.player_id === ctx.p && u.unit_type === o.target,
		)?.count ?? 0;
	return have >= need
		? metAt(ctx.turn, `${have} of ${need} trained`)
		: unmet(`${have} of ${need} trained`);
}

function scoreArmy(
	ctx: Ctx,
	o: Extract<Objective, { kind: "army" }>,
): ObjectiveVerdict {
	const units = ctx.blob.units.filter((u) => {
		if (u.player_xml_id !== ctx.p) return false;
		if (o.types && !o.types.includes(u.unit_type)) return false;
		const stat = UNIT_STATS[u.unit_type];
		if (o.min_strength != null && (stat?.strength ?? 0) < o.min_strength)
			return false;
		if (o.land_only && stat?.naval) return false;
		// A map that leaves the nation to be picked has no unique units to
		// name, so nothing qualifies rather than any nation's.
		if (
			o.unique_only &&
			(stat?.nation == null || stat.nation !== ctx.setup.nation)
		)
			return false;
		if (o.trained_only) {
			if (u.original_tribe != null) return false;
			if (
				u.original_player_xml_id != null &&
				u.original_player_xml_id !== ctx.p
			)
				return false;
		}
		return true;
	});
	const byType = new Map<string, number>();
	for (const u of units)
		byType.set(u.unit_type, (byType.get(u.unit_type) ?? 0) + 1);
	const perType = o.min_per_type ?? 1;
	const types = [...byType.values()].filter((n) => n >= perType).length;
	const parts = [`${units.length} of ${o.count} units`];
	if (o.min_types != null) parts.push(`${types} of ${o.min_types} types`);
	const observed = parts.join(", ");
	const ok =
		units.length >= o.count && (o.min_types == null || types >= o.min_types);
	return ok ? metAt(ctx.turn, observed) : unmet(observed);
}

function scoreCity(
	ctx: Ctx,
	o: Extract<Objective, { kind: "city" }>,
): ObjectiveVerdict {
	const need = o.count ?? 1;
	const improvements = ownedImprovements(ctx).filter(
		(i) => !isUnderConstruction(i),
	);
	const minCulture = o.culture == null ? -1 : cultureRank(o.culture);
	const qualifying = ownedCities(ctx).filter((c) => {
		if (o.capital && !c.is_capital) return false;
		if (cultureRank(c.culture_level) < minCulture) return false;
		// Null is "not recorded", not neutral — it never satisfies a floor.
		if (
			o.min_happiness != null &&
			(c.happiness_level == null || c.happiness_level < o.min_happiness)
		)
			return false;
		const mine = improvements.filter((i) => i.city_xml_id === c.city_id);
		for (const [imp, n] of Object.entries(o.improvements ?? {})) {
			if (mine.filter((i) => matchesImprovement(i.improvement, imp)).length < n)
				return false;
		}
		for (const [spec, n] of Object.entries(o.specialists ?? {})) {
			if (mine.filter((i) => i.specialist === spec).length < n) return false;
		}
		return true;
	});
	const observed = `${qualifying.length} of ${need} cities qualify`;
	return qualifying.length >= need
		? metAt(ctx.turn, observed)
		: unmet(observed);
}

/** The turn a tile first came into the player's hands, from the ownership log. */
function capturedTurn(ctx: Ctx, tileXmlId: number | undefined): number | null {
	if (tileXmlId == null) return null;
	const flips = ctx.blob.tile_ownership_history
		.filter(
			(t) => t.tile_xml_id === tileXmlId && t.owner_player_xml_id === ctx.p,
		)
		.map((t) => t.turn);
	return flips.length ? Math.min(...flips) : null;
}

function scoreCapture(
	ctx: Ctx,
	o: Extract<Objective, { kind: "capture" }>,
): ObjectiveVerdict {
	const need = o.count ?? 1;
	const capitalOnly = o.capital ?? false;
	const cities = ctx.blob.city_statistics.cities;
	// A player's capital is their first city — founded on their turn 1.
	const capitalsByFounder = new Map<number, number>();
	for (const c of cities) {
		if (c.first_owner_player_xml_id == null) continue;
		const cur = capitalsByFounder.get(c.first_owner_player_xml_id);
		if (cur == null || c.founded_turn < cities[cur].founded_turn) {
			capitalsByFounder.set(c.first_owner_player_xml_id, cities.indexOf(c));
		}
	}
	const captured = ownedCities(ctx).filter((c) => {
		if (
			c.first_owner_player_xml_id == null ||
			c.first_owner_player_xml_id === ctx.p
		)
			return false;
		return (
			!capitalOnly ||
			cities[capitalsByFounder.get(c.first_owner_player_xml_id)!] === c
		);
	});
	const what = capitalOnly ? "capitals" : "cities";
	if (captured.length < need)
		return unmet(`${captured.length} of ${need} ${what} captured`);
	const turns = captured
		.map((c) => capturedTurn(ctx, c.tile_xml_id) ?? ctx.turn)
		.sort((a, b) => a - b);
	return deadline(
		ctx,
		turns[need - 1],
		o.by_turn,
		`${captured.length} of ${need} ${what} captured`,
	);
}

function scoreReligion(
	ctx: Ctx,
	o: Extract<Objective, { kind: "religion" }>,
): ObjectiveVerdict {
	const founded = ctx.blob.game_religions.filter(
		(r) =>
			r.founder_player_xml_id === ctx.p &&
			(o.target === ANY_RELIGION || r.religion_name === o.target),
	);
	if (!founded.length) return unmet("not founded");
	const state = playerDetails(ctx.blob, ctx.p)?.state_religion ?? null;
	const qualifying = founded.filter((r) => {
		if (o.state_religion && state !== r.religion_name) return false;
		if (o.min_theology_tier != null) {
			const best = Math.max(
				0,
				...(r.theologies ?? []).map((t) => THEOLOGY_TIER[t] ?? 0),
			);
			if (best < o.min_theology_tier) return false;
		}
		return true;
	});
	if (!qualifying.length) {
		// Explain the closest miss: a religion that is already the state
		// religion fell short on theology; otherwise it isn't the state one.
		const r =
			founded.find((x) => !o.state_religion || state === x.religion_name) ??
			founded[0];
		const why =
			o.state_religion && state !== r.religion_name
				? "not the state religion"
				: "theology tier too low";
		return unmet(
			`${r.religion_name === o.target ? "founded" : `founded ${r.religion_name}`} on turn ${r.founded_turn ?? "?"}, but ${why}`,
		);
	}
	// The deadline governs the founding; the extras are read at the save.
	const foundedTurn = Math.min(
		...qualifying.map((r) => r.founded_turn ?? ctx.turn),
	);
	const v = deadline(ctx, foundedTurn, o.by_turn, "Founded");
	if (v.met && (o.state_religion || o.min_theology_tier != null))
		v.met_turn = ctx.turn;
	return v;
}

function scoreCognomen(
	ctx: Ctx,
	o: Extract<Objective, { kind: "cognomen" }>,
): ObjectiveVerdict {
	const leaderId =
		playerDetails(ctx.blob, ctx.p)?.leader_character_xml_id ?? null;
	const leader = ctx.blob.characters.find((c) => c.xml_id === leaderId);
	if (!leader) return unmet("no reigning leader");
	if (leader.cognomen !== o.target) {
		return unmet(
			leader.cognomen
				? `the leader is called ${leader.cognomen}`
				: "the leader has no cognomen",
		);
	}
	return metAt(ctx.turn, "the leader carries it");
}

/**
 * A per-turn series for the player, as (turn, value) pairs in turn order.
 * The blob's history arrays are turn-ordered as parsed, but nothing pins
 * that, and both callers lean on it (the first hit, the last value) — so
 * the sort lives here rather than in each of them.
 */
function metricSeries(
	ctx: Ctx,
	metric: string,
	measure: "rate" | "cumulative",
): Array<[number, number]> {
	const b = ctx.blob;
	const pick = <T extends { turn: number }>(
		rows: T[] | undefined,
		f: (r: T) => number | null | undefined,
	) =>
		(rows ?? [])
			.flatMap((r): Array<[number, number]> => {
				const v = f(r);
				return v == null ? [] : [[r.turn, v]];
			})
			.sort((a, b) => a[0] - b[0]);
	if (metric.startsWith("YIELD_")) {
		const y = b.yield_history.find(
			(h) => h.player_id === ctx.p && h.yield_type === metric,
		);
		return pick(y?.data, (d) => d[measure]);
	}
	switch (metric) {
		case "points":
		case "military_power":
		case "legitimacy":
			return pick(
				b.player_history.find((h) => h.player_id === ctx.p)?.history,
				(d) => d[metric],
			);
		case "tech_count":
			return pick(
				b.tech_discovery_history.find((h) => h.player_id === ctx.p)?.data,
				(d) => d.tech_count,
			);
		case "law_count":
			return pick(
				b.law_adoption_history.find((h) => h.player_id === ctx.p)?.data,
				(d) => d.law_count,
			);
		case "cities_founded": {
			const turns = b.city_statistics.cities
				.filter((c) => c.first_owner_player_xml_id === ctx.p)
				.map((c) => c.founded_turn)
				.sort((a, b) => a - b);
			return turns.map((t, i) => [t, i + 1]);
		}
		default:
			return [];
	}
}

function scoreMetric(
	ctx: Ctx,
	o: Extract<Objective, { kind: "metric" }>,
): ObjectiveVerdict {
	const series = metricSeries(ctx, o.metric, o.measure ?? "rate");
	const limit = limitOf(ctx, o.by_turn);
	const inWindow = series.filter(([t]) => t <= limit);
	const hit = inWindow.find(([, v]) => v >= o.value);
	if (hit) return metAt(hit[0], `reached ${fmt(hit[1])} on turn ${hit[0]}`);
	if (!inWindow.length) return unmet("no data");
	const peak = inWindow.reduce((a, b) => (b[1] > a[1] ? b : a));
	const late = series.find(([t, v]) => t > limit && v >= o.value);
	return unmet(
		late
			? `reached ${fmt(late[1])} on turn ${late[0]}, after the turn-${o.by_turn} deadline`
			: `peak ${fmt(peak[1])} on turn ${peak[0]}`,
	);
}

function scoreVictory(
	ctx: Ctx,
	o: Extract<Objective, { kind: "victory" }>,
): ObjectiveVerdict {
	const m = ctx.blob.match_metadata;
	const won = m.game_over && m.winner?.winner_player_xml_id === ctx.p;
	if (!won) return unmet("not won");
	return deadline(ctx, ctx.turn, o.by_turn, "Won");
}

function fmt(n: number): string {
	return Number.isInteger(n) ? n.toLocaleString("en-US") : n.toFixed(1);
}

function scoreObjective(ctx: Ctx, o: Objective): ObjectiveVerdict {
	switch (o.kind) {
		case "tech":
			return scoreTech(ctx, o);
		case "build":
			return scoreBuild(ctx, o);
		case "unit":
			return scoreUnit(ctx, o);
		case "army":
			return scoreArmy(ctx, o);
		case "city":
			return scoreCity(ctx, o);
		case "capture":
			return scoreCapture(ctx, o);
		case "religion":
			return scoreReligion(ctx, o);
		case "cognomen":
			return scoreCognomen(ctx, o);
		case "metric":
			return scoreMetric(ctx, o);
		case "victory":
			return scoreVictory(ctx, o);
	}
}

// ---------------------------------------------------------------------------
// Criteria (§3.3) — all read at the save's state
// ---------------------------------------------------------------------------

function verdict(
	kind: Criterion["kind"],
	met: boolean,
	detail: string,
): CriterionVerdict {
	return { kind, met, detail };
}

function scoreFamilies(
	ctx: Ctx,
	c: Extract<Criterion, { kind: "families" }>,
): CriterionVerdict {
	const mine = ctx.blob.families.filter((f) => f.player_xml_id === ctx.p);
	if (c.count?.min != null && mine.length < c.count.min) {
		return verdict(
			c.kind,
			false,
			`${mine.length} families, at least ${c.count.min} required`,
		);
	}
	if (c.count?.max != null && mine.length > c.count.max) {
		return verdict(
			c.kind,
			false,
			`${mine.length} families, at most ${c.count.max} allowed`,
		);
	}
	const inScope =
		c.scope === "seated"
			? mine.filter((f) => f.seat_city_xml_id != null)
			: mine;
	const failing: string[] = [];
	for (const f of inScope) {
		const latest = ctx.blob.family_opinion_history
			.filter(
				(h) => h.player_xml_id === ctx.p && h.family_name === f.family_name,
			)
			.reduce<{
				turn: number;
				opinion: number;
			} | null>(
				(best, h) => (best == null || h.turn > best.turn ? h : best),
				null,
			);
		if (latest == null) failing.push(`${f.family_name} (no opinion recorded)`);
		else if (latest.opinion < c.min_opinion)
			failing.push(`${f.family_name} (${latest.opinion})`);
	}
	if (failing.length)
		return verdict(
			c.kind,
			false,
			`below ${c.min_opinion}: ${failing.join(", ")}`,
		);
	return verdict(
		c.kind,
		true,
		`${inScope.length} ${c.scope === "seated" ? "seated " : ""}families at or above ${c.min_opinion}`,
	);
}

function scoreCities(
	ctx: Ctx,
	c: Extract<Criterion, { kind: "cities" }>,
): CriterionVerdict {
	const cities = ownedCities(ctx).filter(
		(x) => c.scope === "all" || x.first_owner_player_xml_id === ctx.p,
	);
	const damaged = cities.filter((x) => (x.damage ?? 0) > 0);
	if (damaged.length)
		return verdict(
			c.kind,
			false,
			`${damaged.length} of ${cities.length} cities damaged`,
		);
	return verdict(c.kind, true, `${cities.length} cities undamaged`);
}

function scoreLeader(
	ctx: Ctx,
	c: Extract<Criterion, { kind: "leader" }>,
): CriterionVerdict {
	const base = new Set(ctx.setup.leader_traits);
	const leaderId =
		ctx.setup.leader_character_xml_id ?? firstLeader(ctx.blob, ctx.p);
	const picked = startingTraits(ctx.blob, leaderId).filter((t) => !base.has(t));
	const all = new Set([...base, ...picked]);
	if (c.standard_traits_only && ctx.setup.leader_is_custom) {
		const dynasty = picked.filter(isDynastyTrait);
		if (dynasty.length)
			return verdict(
				c.kind,
				false,
				`dynasty trait picked: ${dynasty.join(", ")}`,
			);
	}
	const missing = (c.required_traits ?? []).filter((t) => !all.has(t));
	if (missing.length)
		return verdict(
			c.kind,
			false,
			`required trait missing: ${missing.join(", ")}`,
		);
	if (!ctx.setup.leader_is_custom && !c.required_traits?.length) {
		return verdict(c.kind, true, "the map's leader is not custom");
	}
	return verdict(
		c.kind,
		true,
		picked.length ? `picked ${picked.join(", ")}` : "no traits picked",
	);
}

function scoreEconomy(
	ctx: Ctx,
	c: Extract<Criterion, { kind: "economy" }>,
): CriterionVerdict {
	const failing: string[] = [];
	for (const [y, min] of Object.entries(c.min_rates)) {
		const series = metricSeries(ctx, y, "rate");
		const last = series.length ? series[series.length - 1][1] : null;
		if (last == null || last < min)
			failing.push(`${y} ${last == null ? "unknown" : fmt(last)}`);
	}
	if (failing.length)
		return verdict(c.kind, false, `below the floor: ${failing.join(", ")}`);
	return verdict(c.kind, true, "every listed yield at or above its floor");
}

function scoreMaxCities(
	ctx: Ctx,
	c: Extract<Criterion, { kind: "max_cities" }>,
): CriterionVerdict {
	const n = ownedCities(ctx).length;
	return verdict(c.kind, n <= c.n, `${n} of at most ${c.n} cities`);
}

function scoreCriterion(ctx: Ctx, c: Criterion): CriterionVerdict {
	switch (c.kind) {
		case "families":
			return scoreFamilies(ctx, c);
		case "cities":
			return scoreCities(ctx, c);
		case "leader":
			return scoreLeader(ctx, c);
		case "economy":
			return scoreEconomy(ctx, c);
		case "max_cities":
			return scoreMaxCities(ctx, c);
	}
}

// ---------------------------------------------------------------------------
// The verdict (§5)
// ---------------------------------------------------------------------------

export function scoreChallenge(
	rules: ChallengeRules,
	blob: ScorableBlob,
): Verdict {
	const identity = checkIdentity(rules.setup, blob);
	const ctx: Ctx = {
		blob,
		setup: rules.setup,
		p: rules.setup.player_index,
		turn: blob.match_metadata.total_turns,
	};
	const objectives = rules.objectives.map((o) => scoreObjective(ctx, o));
	const criteria = rules.criteria.map((c) => scoreCriterion(ctx, c));
	const met =
		identity.ok &&
		objectives.every((o) => o.met) &&
		criteria.every((c) => c.met);
	const metTurns = objectives
		.map((o) => o.met_turn)
		.filter((t): t is number => t != null);
	return {
		identity,
		objectives,
		criteria,
		met,
		score_turn: met ? ctx.turn : null,
		earliest_turn: met && metTurns.length ? Math.max(...metTurns) : null,
	};
}
