// Canonical map_script options + per-script applicability accepted by the API.
//
// Mirror of the data in src/lib/generated/{map-option-defs,map-script-options}.ts.
// Keep these two in sync when re-baking or when a new DLC ships.
//
// Why duplicated: cloud/ is a separate package with its own tsconfig
// (cloud/tsconfig.json), bundled by wrangler/esbuild — importing from
// ../../../src/lib/generated/* would pull in SvelteKit-shaped path
// resolution the Worker bundle doesn't need.
//
// Drift safety nets:
//   - canonical-map-options.test.ts: asserts this file matches the
//     generated SvelteKit module exactly (key set, choices per option,
//     toggle/select kind, script→options mapping).
//   - Create/patch integration tests exercise the schema end-to-end.

export type CanonicalMapOption =
	| { readonly kind: "toggle" }
	| { readonly kind: "select"; readonly choices: readonly string[] };

export const CANONICAL_MAP_OPTIONS: Readonly<
	Record<string, CanonicalMapOption>
> = {
	// Synthetic globals: not registered via options.Add(...) in C# — sourced
	// from mapAspectRatio.xml / mapSize.xml directly. See bake-map-options.ts.
	MAPASPECTRATIO: {
		kind: "select",
		choices: [
			"MAPASPECTRATIO_SQUARE",
			"MAPASPECTRATIO_WIDE",
			"MAPASPECTRATIO_ULTRAWIDE",
			"MAPASPECTRATIO_DYNAMIC",
		],
	},
	MAPSIZE: {
		kind: "select",
		choices: [
			"MAPSIZE_SMALLEST",
			"MAPSIZE_TINY",
			"MAPSIZE_SMALL",
			"MAPSIZE_MEDIUM",
			"MAPSIZE_LARGE",
			"MAPSIZE_HUGE",
			"MAPSIZE_RANDOM",
		],
	},
	MAP_OPTIONS_ARCHIPELAGO_LANDMASS: {
		kind: "select",
		choices: [
			"MAP_OPTION_ARCHIPELAGO_LANDMASS_SMALL",
			"MAP_OPTION_ARCHIPELAGO_LANDMASS_MEDIUM",
			"MAP_OPTION_ARCHIPELAGO_LANDMASS_LARGE",
		],
	},
	MAP_OPTIONS_CITY_SITE_DENSITY: {
		kind: "select",
		choices: [
			"MAP_OPTION_CITY_SITE_DENSITY_HIGH",
			"MAP_OPTION_CITY_SITE_DENSITY_MEDIUM",
			"MAP_OPTION_CITY_SITE_DENSITY_LOW",
			"MAP_OPTION_CITY_SITE_DENSITY_RANDOM",
		],
	},
	MAP_OPTIONS_CITY_SITE_NUMBER: {
		kind: "select",
		choices: [
			"MAP_OPTION_CITY_SITE_NUMBER_HIGH",
			"MAP_OPTION_CITY_SITE_NUMBER_MEDIUM",
			"MAP_OPTION_CITY_SITE_NUMBER_LOW",
			"MAP_OPTION_CITY_SITE_NUMBER_SINGLE",
		],
	},
	MAP_OPTIONS_CONTINENTS_NUMBER: {
		kind: "select",
		choices: [
			"MAP_OPTION_CONTINENTS_NUMBER_TWO",
			"MAP_OPTION_CONTINENTS_NUMBER_THREE",
			"MAP_OPTION_CONTINENTS_NUMBER_RANDOM",
		],
	},
	MAP_OPTIONS_DESERT_COAST: {
		kind: "select",
		choices: [
			"MAP_OPTION_DESERT_COAST_NONE",
			"MAP_OPTION_DESERT_COAST_DRY",
			"MAP_OPTION_DESERT_COAST_LUSH",
			"MAP_OPTION_DESERT_COAST_RANDOM",
		],
	},
	MAP_OPTIONS_DESERT_SIZE: {
		kind: "select",
		choices: ["MAP_OPTION_DESERT_SIZE_NORMAL", "MAP_OPTION_DESERT_SIZE_DOUBLE"],
	},
	MAP_OPTIONS_DONUT_IRREGULARITY: {
		kind: "select",
		choices: [
			"MAP_OPTION_DONUT_IRREGULARITY_LOW",
			"MAP_OPTION_DONUT_IRREGULARITY_MEDIUM",
			"MAP_OPTION_DONUT_IRREGULARITY_HIGH",
		],
	},
	MAP_OPTIONS_MULTI_ARCHIPELAGO_WATER_SIZE: {
		kind: "select",
		choices: [
			"MAP_OPTION_ARCHIPELAGO_WATER_SIZE_LARGE",
			"MAP_OPTION_ARCHIPELAGO_WATER_SIZE_SMALL",
			"MAP_OPTION_ARCHIPELAGO_WATER_SIZE_MERGED",
			"MAP_OPTION_WATER_SIZE_RANDOM",
		],
	},
	MAP_OPTIONS_MULTI_ARID_WATER_SIZE: {
		kind: "select",
		choices: [
			"MAP_OPTION_ARID_WATER_SIZE_LARGE",
			"MAP_OPTION_ARID_WATER_SIZE_SMALL",
			"MAP_OPTION_WATER_SIZE_RANDOM",
		],
	},
	MAP_OPTIONS_MULTI_CALAMITIES_DESOLATION_OPTIONS_DESOLATION: {
		kind: "select",
		choices: [
			"MAP_OPTION_CALAMITIES_DESOLATION_OPTIONS_DESOLATION_SLOW",
			"MAP_OPTION_CALAMITIES_DESOLATION_OPTIONS_DESOLATION_MEDIUM",
			"MAP_OPTION_CALAMITIES_DESOLATION_OPTIONS_DESOLATION_FAST",
		],
	},
	MAP_OPTIONS_MULTI_CALAMITIES_EBBING_SEA_OPTIONS_EVAPORATION: {
		kind: "select",
		choices: [
			"MAP_OPTION_CALAMITIES_EBBING_SEA_OPTIONS_EVAPORATION_SLOW",
			"MAP_OPTION_CALAMITIES_EBBING_SEA_OPTIONS_EVAPORATION_MEDIUM",
			"MAP_OPTION_CALAMITIES_EBBING_SEA_OPTIONS_EVAPORATION_FAST",
		],
	},
	MAP_OPTIONS_MULTI_CALAMITIES_TUMBLING_MOUNTAIN_OPTIONS_TIME: {
		kind: "select",
		choices: [
			"MAP_OPTION_CALAMITIES_TUMBLING_MOUNTAIN_OPTIONS_TIME_SHORT",
			"MAP_OPTION_CALAMITIES_TUMBLING_MOUNTAIN_OPTIONS_TIME_MEDIUM",
			"MAP_OPTION_CALAMITIES_TUMBLING_MOUNTAIN_OPTIONS_TIME_LONG",
			"MAP_OPTION_CALAMITIES_TUMBLING_MOUNTAIN_OPTIONS_TIME_GRADUAL",
			"MAP_OPTION_CALAMITIES_TUMBLING_MOUNTAIN_OPTIONS_TIME_NEVER",
		],
	},
	MAP_OPTIONS_MULTI_CONTINENT_TERRAIN: {
		kind: "select",
		choices: [
			"MAP_OPTION_CONTINENT_TERRAIN_NONE",
			"MAP_OPTION_CONTINENT_TERRAIN_EITHER",
			"MAP_OPTION_CONTINENT_TERRAIN_TUNDRA",
			"MAP_OPTION_CONTINENT_TERRAIN_DESERT",
		],
	},
	MAP_OPTIONS_MULTI_CONTINENT_TRIBES: {
		kind: "select",
		choices: [
			"MAP_OPTION_CONTINENT_TRIBES_SCATTERED",
			"MAP_OPTION_CONTINENT_TRIBES_QUADRANTS",
			"MAP_OPTION_CONTINENT_TRIBES_RANDOM",
		],
	},
	MAP_OPTIONS_MULTI_DISJUNCTION_CONTINENTS: {
		kind: "select",
		choices: [
			"MAP_OPTION_DISJUNCTION_CONTINENTS_TWO_EVEN",
			"MAP_OPTION_DISJUNCTION_CONTINENTS_THREE_EVEN",
			"MAP_OPTION_DISJUNCTION_CONTINENTS_THREE_UNEVEN",
			"MAP_OPTION_DISJUNCTION_CONTINENTS_TEAMS",
			"MAP_OPTION_DISJUNCTION_CONTINENTS_WEIGHTED_RANDOM",
		],
	},
	MAP_OPTIONS_MULTI_DOTA_BOUNDARY_TERRAIN: {
		kind: "select",
		choices: [
			"MAP_OPTION_TERRAIN_JUNGLE",
			"MAP_OPTION_TERRAIN_MOUNTAINS",
			"MAP_OPTION_TERRAIN_WATER",
			"MAP_OPTION_TERRAIN_SAND",
		],
	},
	MAP_OPTIONS_MULTI_DOTA_RIVER_WIDTH: {
		kind: "select",
		choices: ["MAP_OPTION_RIVER_NARROW", "MAP_OPTION_RIVER_WIDE"],
	},
	MAP_OPTIONS_MULTI_NORTHERN_OCEAN_TRIBES: {
		kind: "select",
		choices: [
			"MAP_OPTION_NORTHERN_OCEAN_TRIBES_NATIVE",
			"MAP_OPTION_NORTHERN_OCEAN_TRIBES_RANDOM",
		],
	},
	MAP_OPTIONS_MULTI_RESOURCE_DENSITY: {
		kind: "select",
		choices: [
			"MAP_OPTION_HIGH_RESOURCES",
			"MAP_OPTION_MEDIUM_RESOURCES",
			"MAP_OPTION_LOW_RESOURCES",
			"MAP_OPTION_RANDOM_RESOURCES",
		],
	},
	MAP_OPTIONS_MULTI_SEASIDE_TERRAIN_TYPE_VARIATION: {
		kind: "select",
		choices: [
			"MAP_OPTION_SEASIDE_TERRAIN_TUNDRA",
			"MAP_OPTION_SEASIDE_TERRAIN_DESERT",
			"MAP_OPTION_SEASIDE_TERRAIN_RANDOM",
		],
	},
	MAP_OPTIONS_MULTI_SEASIDE_TRIBES: {
		kind: "select",
		choices: [
			"MAP_OPTION_SEASIDE_TRIBES_FIVE",
			"MAP_OPTION_SEASIDE_TRIBES_FOUR",
			"MAP_OPTION_SEASIDE_TRIBES_THREE",
			"MAP_OPTION_SEASIDE_TRIBES_RANDOM",
		],
	},
	MAP_OPTIONS_PLAYER_CONTINENTS_EXTRA: {
		kind: "select",
		choices: [
			"MAP_OPTION_PLAYER_CONTINENTS_EXTRA_NONE",
			"MAP_OPTION_PLAYER_CONTINENTS_EXTRA_ONE",
			"MAP_OPTION_PLAYER_CONTINENTS_EXTRA_TWO",
			"MAP_OPTION_PLAYER_CONTINENTS_EXTRA_RANDOM",
		],
	},
	MAP_OPTIONS_REJUVENATION_COAST: {
		kind: "select",
		choices: [
			"MAP_OPTION_REJUVENATION_COAST_NONE",
			"MAP_OPTION_REJUVENATION_COAST_DRY",
		],
	},
	MAP_OPTIONS_REJUVENATION_START: {
		kind: "select",
		choices: [
			"MAP_OPTION_REJUVENATION_START_ANY",
			"MAP_OPTION_REJUVENATION_START_COAST",
			"MAP_OPTION_REJUVENATION_START_INLAND",
		],
	},
	MAP_OPTIONS_SINGLE_CONNECTED_STARTS: { kind: "toggle" },
	MAP_OPTIONS_SINGLE_EXTRA_MOUNTAINS: { kind: "toggle" },
	MAP_OPTIONS_SINGLE_EXTRA_WATER: { kind: "toggle" },
	MAP_OPTIONS_SINGLE_FAIR_STARTS: { kind: "toggle" },
	MAP_OPTIONS_SINGLE_GOOD_PLAYER_START_RESOURCES: { kind: "toggle" },
	MAP_OPTIONS_SINGLE_KING_OF_THE_HILL: { kind: "toggle" },
	MAP_OPTIONS_SINGLE_MIRROR: { kind: "toggle" },
	MAP_OPTIONS_SINGLE_POINT_SYMMETRY: { kind: "toggle" },
};

// Per-script option applicability. Each entry is the list of option zTypes
// (matching CANONICAL_MAP_OPTIONS keys) that this script registers — globals
// from DefaultMapScript first, then script-specific in declaration order.
export const CANONICAL_SCRIPT_OPTIONS: Readonly<
	Record<string, readonly string[]>
> = {
	MAPCLASS_MapScripLakesAndGulfs: [
		"MAPSIZE",
		"MAPASPECTRATIO",
		"MAP_OPTIONS_MULTI_RESOURCE_DENSITY",
		"MAP_OPTIONS_CITY_SITE_DENSITY",
		"MAP_OPTIONS_CITY_SITE_NUMBER",
		"MAP_OPTIONS_SINGLE_GOOD_PLAYER_START_RESOURCES",
		"MAP_OPTIONS_MULTI_SEASIDE_TERRAIN_TYPE_VARIATION",
		"MAP_OPTIONS_MULTI_SEASIDE_TRIBES",
		"MAP_OPTIONS_SINGLE_CONNECTED_STARTS",
	],
	MAPCLASS_MapScriptArchipelago: [
		"MAPSIZE",
		"MAPASPECTRATIO",
		"MAP_OPTIONS_MULTI_RESOURCE_DENSITY",
		"MAP_OPTIONS_CITY_SITE_DENSITY",
		"MAP_OPTIONS_CITY_SITE_NUMBER",
		"MAP_OPTIONS_SINGLE_GOOD_PLAYER_START_RESOURCES",
		"MAP_OPTIONS_ARCHIPELAGO_LANDMASS",
		"MAP_OPTIONS_MULTI_ARCHIPELAGO_WATER_SIZE",
		"MAP_OPTIONS_MULTI_SEASIDE_TRIBES",
		"MAP_OPTIONS_SINGLE_POINT_SYMMETRY",
		"MAP_OPTIONS_SINGLE_MIRROR",
	],
	MAPCLASS_MapScriptAridPlateau: [
		"MAPSIZE",
		"MAPASPECTRATIO",
		"MAP_OPTIONS_MULTI_RESOURCE_DENSITY",
		"MAP_OPTIONS_CITY_SITE_DENSITY",
		"MAP_OPTIONS_CITY_SITE_NUMBER",
		"MAP_OPTIONS_SINGLE_GOOD_PLAYER_START_RESOURCES",
		"MAP_OPTIONS_MULTI_ARID_WATER_SIZE",
		"MAP_OPTIONS_SINGLE_POINT_SYMMETRY",
		"MAP_OPTIONS_SINGLE_MIRROR",
	],
	MAPCLASS_MapScriptBay: [
		"MAPSIZE",
		"MAPASPECTRATIO",
		"MAP_OPTIONS_MULTI_RESOURCE_DENSITY",
		"MAP_OPTIONS_CITY_SITE_DENSITY",
		"MAP_OPTIONS_CITY_SITE_NUMBER",
		"MAP_OPTIONS_SINGLE_GOOD_PLAYER_START_RESOURCES",
		"MAP_OPTIONS_MULTI_SEASIDE_TERRAIN_TYPE_VARIATION",
		"MAP_OPTIONS_MULTI_SEASIDE_TRIBES",
	],
	MAPCLASS_MapScriptCoastalRainBasin: [
		"MAPSIZE",
		"MAPASPECTRATIO",
		"MAP_OPTIONS_MULTI_RESOURCE_DENSITY",
		"MAP_OPTIONS_CITY_SITE_DENSITY",
		"MAP_OPTIONS_CITY_SITE_NUMBER",
		"MAP_OPTIONS_SINGLE_GOOD_PLAYER_START_RESOURCES",
		"MAP_OPTIONS_SINGLE_POINT_SYMMETRY",
		"MAP_OPTIONS_SINGLE_MIRROR",
	],
	MAPCLASS_MapScriptContinent: [
		"MAPSIZE",
		"MAPASPECTRATIO",
		"MAP_OPTIONS_MULTI_RESOURCE_DENSITY",
		"MAP_OPTIONS_CITY_SITE_DENSITY",
		"MAP_OPTIONS_CITY_SITE_NUMBER",
		"MAP_OPTIONS_SINGLE_GOOD_PLAYER_START_RESOURCES",
		"MAP_OPTIONS_MULTI_CONTINENT_TRIBES",
		"MAP_OPTIONS_MULTI_CONTINENT_TERRAIN",
		"MAP_OPTIONS_SINGLE_POINT_SYMMETRY",
		"MAP_OPTIONS_SINGLE_MIRROR",
	],
	MAPCLASS_MapScriptContinents: [
		"MAPSIZE",
		"MAPASPECTRATIO",
		"MAP_OPTIONS_MULTI_RESOURCE_DENSITY",
		"MAP_OPTIONS_CITY_SITE_DENSITY",
		"MAP_OPTIONS_CITY_SITE_NUMBER",
		"MAP_OPTIONS_SINGLE_GOOD_PLAYER_START_RESOURCES",
		"MAP_OPTIONS_CONTINENTS_NUMBER",
		"MAP_OPTIONS_SINGLE_POINT_SYMMETRY",
		"MAP_OPTIONS_SINGLE_MIRROR",
	],
	MAPCLASS_MapScriptDesert: [
		"MAPSIZE",
		"MAPASPECTRATIO",
		"MAP_OPTIONS_MULTI_RESOURCE_DENSITY",
		"MAP_OPTIONS_CITY_SITE_DENSITY",
		"MAP_OPTIONS_CITY_SITE_NUMBER",
		"MAP_OPTIONS_SINGLE_GOOD_PLAYER_START_RESOURCES",
		"MAP_OPTIONS_DESERT_COAST",
		"MAP_OPTIONS_DESERT_SIZE",
		"MAP_OPTIONS_SINGLE_POINT_SYMMETRY",
		"MAP_OPTIONS_SINGLE_MIRROR",
	],
	MAPCLASS_MapScriptDesolation: [
		"MAPSIZE",
		"MAPASPECTRATIO",
		"MAP_OPTIONS_MULTI_RESOURCE_DENSITY",
		"MAP_OPTIONS_CITY_SITE_DENSITY",
		"MAP_OPTIONS_CITY_SITE_NUMBER",
		"MAP_OPTIONS_SINGLE_GOOD_PLAYER_START_RESOURCES",
		"MAP_OPTIONS_MULTI_CALAMITIES_DESOLATION_OPTIONS_DESOLATION",
	],
	MAPCLASS_MapScriptDisjunction: [
		"MAPSIZE",
		"MAPASPECTRATIO",
		"MAP_OPTIONS_MULTI_RESOURCE_DENSITY",
		"MAP_OPTIONS_CITY_SITE_DENSITY",
		"MAP_OPTIONS_CITY_SITE_NUMBER",
		"MAP_OPTIONS_SINGLE_GOOD_PLAYER_START_RESOURCES",
		"MAP_OPTIONS_MULTI_DISJUNCTION_CONTINENTS",
		"MAP_OPTIONS_SINGLE_KING_OF_THE_HILL",
	],
	MAPCLASS_MapScriptDonut: [
		"MAPSIZE",
		"MAPASPECTRATIO",
		"MAP_OPTIONS_MULTI_RESOURCE_DENSITY",
		"MAP_OPTIONS_CITY_SITE_DENSITY",
		"MAP_OPTIONS_CITY_SITE_NUMBER",
		"MAP_OPTIONS_SINGLE_GOOD_PLAYER_START_RESOURCES",
		"MAP_OPTIONS_MULTI_CONTINENT_TRIBES",
		"MAP_OPTIONS_MULTI_CONTINENT_TERRAIN",
		"MAP_OPTIONS_DONUT_IRREGULARITY",
		"MAP_OPTIONS_SINGLE_POINT_SYMMETRY",
		"MAP_OPTIONS_SINGLE_MIRROR",
	],
	MAPCLASS_MapScriptDota: [
		"MAPSIZE",
		"MAPASPECTRATIO",
		"MAP_OPTIONS_MULTI_RESOURCE_DENSITY",
		"MAP_OPTIONS_CITY_SITE_DENSITY",
		"MAP_OPTIONS_CITY_SITE_NUMBER",
		"MAP_OPTIONS_SINGLE_GOOD_PLAYER_START_RESOURCES",
		"MAP_OPTIONS_MULTI_DOTA_BOUNDARY_TERRAIN",
		"MAP_OPTIONS_MULTI_DOTA_RIVER_WIDTH",
		"MAP_OPTIONS_SINGLE_MIRROR",
	],
	MAPCLASS_MapScriptEbbingSea: [
		"MAPSIZE",
		"MAPASPECTRATIO",
		"MAP_OPTIONS_MULTI_RESOURCE_DENSITY",
		"MAP_OPTIONS_CITY_SITE_DENSITY",
		"MAP_OPTIONS_CITY_SITE_NUMBER",
		"MAP_OPTIONS_SINGLE_GOOD_PLAYER_START_RESOURCES",
		"MAP_OPTIONS_ARCHIPELAGO_LANDMASS",
		"MAP_OPTIONS_MULTI_ARCHIPELAGO_WATER_SIZE",
		"MAP_OPTIONS_MULTI_CALAMITIES_EBBING_SEA_OPTIONS_EVAPORATION",
	],
	MAPCLASS_MapScriptHardwoodForest: [
		"MAPSIZE",
		"MAPASPECTRATIO",
		"MAP_OPTIONS_MULTI_RESOURCE_DENSITY",
		"MAP_OPTIONS_CITY_SITE_DENSITY",
		"MAP_OPTIONS_CITY_SITE_NUMBER",
		"MAP_OPTIONS_SINGLE_GOOD_PLAYER_START_RESOURCES",
		"MAP_OPTIONS_SINGLE_POINT_SYMMETRY",
		"MAP_OPTIONS_SINGLE_MIRROR",
	],
	MAPCLASS_MapScriptHighlands: [
		"MAPSIZE",
		"MAPASPECTRATIO",
		"MAP_OPTIONS_MULTI_RESOURCE_DENSITY",
		"MAP_OPTIONS_CITY_SITE_DENSITY",
		"MAP_OPTIONS_CITY_SITE_NUMBER",
		"MAP_OPTIONS_SINGLE_GOOD_PLAYER_START_RESOURCES",
		"MAP_OPTIONS_SINGLE_MIRROR",
	],
	MAPCLASS_MapScriptInlandSea2: [
		"MAPSIZE",
		"MAPASPECTRATIO",
		"MAP_OPTIONS_MULTI_RESOURCE_DENSITY",
		"MAP_OPTIONS_CITY_SITE_DENSITY",
		"MAP_OPTIONS_CITY_SITE_NUMBER",
		"MAP_OPTIONS_SINGLE_GOOD_PLAYER_START_RESOURCES",
		"MAP_OPTIONS_SINGLE_POINT_SYMMETRY",
		"MAP_OPTIONS_SINGLE_MIRROR",
	],
	MAPCLASS_MapScriptMediterrancean: [
		"MAPSIZE",
		"MAPASPECTRATIO",
		"MAP_OPTIONS_MULTI_RESOURCE_DENSITY",
		"MAP_OPTIONS_CITY_SITE_DENSITY",
		"MAP_OPTIONS_CITY_SITE_NUMBER",
		"MAP_OPTIONS_SINGLE_GOOD_PLAYER_START_RESOURCES",
		"MAP_OPTIONS_MULTI_SEASIDE_TERRAIN_TYPE_VARIATION",
		"MAP_OPTIONS_MULTI_SEASIDE_TRIBES",
		"MAP_OPTIONS_SINGLE_FAIR_STARTS",
		"MAP_OPTIONS_SINGLE_CONNECTED_STARTS",
	],
	MAPCLASS_MapScriptNorthernOcean: [
		"MAPSIZE",
		"MAPASPECTRATIO",
		"MAP_OPTIONS_MULTI_RESOURCE_DENSITY",
		"MAP_OPTIONS_CITY_SITE_DENSITY",
		"MAP_OPTIONS_CITY_SITE_NUMBER",
		"MAP_OPTIONS_SINGLE_GOOD_PLAYER_START_RESOURCES",
		"MAP_OPTIONS_MULTI_NORTHERN_OCEAN_TRIBES",
	],
	MAPCLASS_MapScriptPlayerIslands: [
		"MAPSIZE",
		"MAPASPECTRATIO",
		"MAP_OPTIONS_MULTI_RESOURCE_DENSITY",
		"MAP_OPTIONS_CITY_SITE_DENSITY",
		"MAP_OPTIONS_CITY_SITE_NUMBER",
		"MAP_OPTIONS_SINGLE_GOOD_PLAYER_START_RESOURCES",
		"MAP_OPTIONS_PLAYER_CONTINENTS_EXTRA",
		"MAP_OPTIONS_SINGLE_EXTRA_WATER",
	],
	MAPCLASS_MapScriptRejuvenation: [
		"MAPSIZE",
		"MAPASPECTRATIO",
		"MAP_OPTIONS_MULTI_RESOURCE_DENSITY",
		"MAP_OPTIONS_CITY_SITE_DENSITY",
		"MAP_OPTIONS_CITY_SITE_NUMBER",
		"MAP_OPTIONS_SINGLE_GOOD_PLAYER_START_RESOURCES",
		"MAP_OPTIONS_REJUVENATION_COAST",
		"MAP_OPTIONS_REJUVENATION_START",
	],
	MAPCLASS_MapScriptSeaside: [
		"MAPSIZE",
		"MAPASPECTRATIO",
		"MAP_OPTIONS_MULTI_RESOURCE_DENSITY",
		"MAP_OPTIONS_CITY_SITE_DENSITY",
		"MAP_OPTIONS_CITY_SITE_NUMBER",
		"MAP_OPTIONS_SINGLE_GOOD_PLAYER_START_RESOURCES",
		"MAP_OPTIONS_MULTI_SEASIDE_TERRAIN_TYPE_VARIATION",
		"MAP_OPTIONS_MULTI_SEASIDE_TRIBES",
		"MAP_OPTIONS_SINGLE_EXTRA_MOUNTAINS",
		"MAP_OPTIONS_SINGLE_EXTRA_WATER",
	],
	MAPCLASS_MapScriptTumblingMountain: [
		"MAPSIZE",
		"MAPASPECTRATIO",
		"MAP_OPTIONS_MULTI_RESOURCE_DENSITY",
		"MAP_OPTIONS_CITY_SITE_DENSITY",
		"MAP_OPTIONS_CITY_SITE_NUMBER",
		"MAP_OPTIONS_SINGLE_GOOD_PLAYER_START_RESOURCES",
		"MAP_OPTIONS_MULTI_DISJUNCTION_CONTINENTS",
		"MAP_OPTIONS_MULTI_CALAMITIES_TUMBLING_MOUNTAIN_OPTIONS_TIME",
	],
	MAPCLASS_MapscriptJungle: [
		"MAPSIZE",
		"MAPASPECTRATIO",
		"MAP_OPTIONS_MULTI_RESOURCE_DENSITY",
		"MAP_OPTIONS_CITY_SITE_DENSITY",
		"MAP_OPTIONS_CITY_SITE_NUMBER",
		"MAP_OPTIONS_SINGLE_GOOD_PLAYER_START_RESOURCES",
		"MAP_OPTIONS_MULTI_SEASIDE_TERRAIN_TYPE_VARIATION",
		"MAP_OPTIONS_MULTI_SEASIDE_TRIBES",
		"MAP_OPTIONS_SINGLE_POINT_SYMMETRY",
		"MAP_OPTIONS_SINGLE_CONNECTED_STARTS",
	],
	MAPCLASS_MapscriptMountainPass: [
		"MAPSIZE",
		"MAPASPECTRATIO",
		"MAP_OPTIONS_MULTI_RESOURCE_DENSITY",
		"MAP_OPTIONS_CITY_SITE_DENSITY",
		"MAP_OPTIONS_CITY_SITE_NUMBER",
		"MAP_OPTIONS_SINGLE_GOOD_PLAYER_START_RESOURCES",
		"MAP_OPTIONS_SINGLE_POINT_SYMMETRY",
		"MAP_OPTIONS_SINGLE_MIRROR",
	],
	MAPCLASS_MapscriptWetlands: [
		"MAPSIZE",
		"MAPASPECTRATIO",
		"MAP_OPTIONS_MULTI_RESOURCE_DENSITY",
		"MAP_OPTIONS_CITY_SITE_DENSITY",
		"MAP_OPTIONS_CITY_SITE_NUMBER",
		"MAP_OPTIONS_SINGLE_GOOD_PLAYER_START_RESOURCES",
		"MAP_OPTIONS_MULTI_SEASIDE_TRIBES",
		"MAP_OPTIONS_SINGLE_POINT_SYMMETRY",
		"MAP_OPTIONS_SINGLE_MIRROR",
	],
};

// Default value for an option, used by the Worker when pre-populating
// per-script options on tournament create / on add-to-allowed. Returns
// `false` for toggles and the canonical XML default for selects.
//
// Drift-safety check duplicates the generated module's <Default> values;
// the test asserts these stay aligned. Keep alphabetical to match the
// generated module's sort order.
export const CANONICAL_MAP_OPTION_DEFAULTS: Readonly<
	Record<string, string | false>
> = {
	MAPASPECTRATIO: "MAPASPECTRATIO_SQUARE",
	MAPSIZE: "MAPSIZE_SMALLEST",
	MAP_OPTIONS_ARCHIPELAGO_LANDMASS: "MAP_OPTION_ARCHIPELAGO_LANDMASS_SMALL",
	MAP_OPTIONS_CITY_SITE_DENSITY: "MAP_OPTION_CITY_SITE_DENSITY_HIGH",
	MAP_OPTIONS_CITY_SITE_NUMBER: "MAP_OPTION_CITY_SITE_NUMBER_HIGH",
	MAP_OPTIONS_CONTINENTS_NUMBER: "MAP_OPTION_CONTINENTS_NUMBER_RANDOM",
	MAP_OPTIONS_DESERT_COAST: "MAP_OPTION_DESERT_COAST_DRY",
	MAP_OPTIONS_DESERT_SIZE: "MAP_OPTION_DESERT_SIZE_NORMAL",
	MAP_OPTIONS_DONUT_IRREGULARITY: "MAP_OPTION_DONUT_IRREGULARITY_MEDIUM",
	MAP_OPTIONS_MULTI_ARCHIPELAGO_WATER_SIZE: "MAP_OPTION_WATER_SIZE_RANDOM",
	MAP_OPTIONS_MULTI_ARID_WATER_SIZE: "MAP_OPTION_WATER_SIZE_RANDOM",
	MAP_OPTIONS_MULTI_CALAMITIES_DESOLATION_OPTIONS_DESOLATION:
		"MAP_OPTION_CALAMITIES_DESOLATION_OPTIONS_DESOLATION_MEDIUM",
	MAP_OPTIONS_MULTI_CALAMITIES_EBBING_SEA_OPTIONS_EVAPORATION:
		"MAP_OPTION_CALAMITIES_EBBING_SEA_OPTIONS_EVAPORATION_MEDIUM",
	MAP_OPTIONS_MULTI_CALAMITIES_TUMBLING_MOUNTAIN_OPTIONS_TIME:
		"MAP_OPTION_CALAMITIES_TUMBLING_MOUNTAIN_OPTIONS_TIME_MEDIUM",
	MAP_OPTIONS_MULTI_CONTINENT_TERRAIN: "MAP_OPTION_CONTINENT_TERRAIN_NONE",
	MAP_OPTIONS_MULTI_CONTINENT_TRIBES: "MAP_OPTION_CONTINENT_TRIBES_RANDOM",
	MAP_OPTIONS_MULTI_DISJUNCTION_CONTINENTS:
		"MAP_OPTION_DISJUNCTION_CONTINENTS_TEAMS",
	MAP_OPTIONS_MULTI_DOTA_BOUNDARY_TERRAIN: "MAP_OPTION_TERRAIN_JUNGLE",
	MAP_OPTIONS_MULTI_DOTA_RIVER_WIDTH: "MAP_OPTION_RIVER_NARROW",
	MAP_OPTIONS_MULTI_NORTHERN_OCEAN_TRIBES:
		"MAP_OPTION_NORTHERN_OCEAN_TRIBES_NATIVE",
	MAP_OPTIONS_MULTI_RESOURCE_DENSITY: "MAP_OPTION_MEDIUM_RESOURCES",
	MAP_OPTIONS_MULTI_SEASIDE_TERRAIN_TYPE_VARIATION:
		"MAP_OPTION_SEASIDE_TERRAIN_RANDOM",
	MAP_OPTIONS_MULTI_SEASIDE_TRIBES: "MAP_OPTION_SEASIDE_TRIBES_RANDOM",
	MAP_OPTIONS_PLAYER_CONTINENTS_EXTRA:
		"MAP_OPTION_PLAYER_CONTINENTS_EXTRA_NONE",
	MAP_OPTIONS_REJUVENATION_COAST: "MAP_OPTION_REJUVENATION_COAST_DRY",
	MAP_OPTIONS_REJUVENATION_START: "MAP_OPTION_REJUVENATION_START_ANY",
	MAP_OPTIONS_SINGLE_CONNECTED_STARTS: false,
	MAP_OPTIONS_SINGLE_EXTRA_MOUNTAINS: false,
	MAP_OPTIONS_SINGLE_EXTRA_WATER: false,
	MAP_OPTIONS_SINGLE_FAIR_STARTS: false,
	MAP_OPTIONS_SINGLE_GOOD_PLAYER_START_RESOURCES: false,
	MAP_OPTIONS_SINGLE_KING_OF_THE_HILL: false,
	MAP_OPTIONS_SINGLE_MIRROR: false,
	MAP_OPTIONS_SINGLE_POINT_SYMMETRY: false,
};
