// Bake each nation's family pool (cloud/src/generated/family-pools.ts) from
// Reference/XML:
//
//   npx tsx scripts/bake-family-pools.ts
//
// A nation has a fixed pool of families and a player fields exactly three of
// them per game, so a four-family nation leaves one out of every game it ever
// plays. Measuring which one is refused needs the pool, and the pool is the one
// input play data cannot supply: a family nobody ever fields leaves no trace in
// any game. It has to come from game content.
//
// Source is family.xml, where each family carries its FamilyClass and an
// abNation map of the nations it belongs to. Emitted to cloud/ because the cut
// statistics are computed in the Worker, next to the games they read.
//
// The pool is by family CLASS, not by family: the classes are what repeat
// across nations and what a cut statistic compares. Two families of the same
// class in one nation's pool would collapse to one entry, which would silently
// break the three-of-N arithmetic — so that fails the bake instead.

import { writeFileSync } from "node:fs";
import { dirname, resolve } from "node:path";
import { fileURLToPath } from "node:url";
import { readFamilyPools } from "./lib/family-pools";

const __dirname = dirname(fileURLToPath(import.meta.url));
const REPO_ROOT = resolve(__dirname, "..");
const OUT = resolve(REPO_ROOT, "cloud/src/generated/family-pools.ts");

async function main(): Promise<void> {
	const pools = readFamilyPools();
	const nations = [...pools.keys()].sort();

	const rows = nations
		.map((nation) => {
			const classes = [...pools.get(nation)!].sort();
			const body = classes.map((c) => `\t\t${JSON.stringify(c)},`).join("\n");
			return `\t${JSON.stringify(nation)}: [\n${body}\n\t],`;
		})
		.join("\n");

	const out =
		`// Generated by scripts/bake-family-pools.ts — do not edit by hand.\n` +
		`// Source: Reference/XML/Infos/family.xml (FamilyClass + abNation).\n` +
		`// Re-run when a patch changes a nation's families.\n\n` +
		`// Every family class a nation may field. A player fields exactly three of\n` +
		`// them per game, so |pool| decides the chance baseline a cut rate is\n` +
		`// measured against: 3/4 of a four-family pool is kept by indifference\n` +
		`// alone, and only 3/6 of Maurya's. A nation whose pool is three fields all\n` +
		`// of it every game and says nothing about preference — see FORCED_POOL_MAX\n` +
		`// in ../stats/family-cuts.\n` +
		`export const NATION_FAMILY_POOLS: Readonly<\n` +
		`\tRecord<string, readonly string[]>\n` +
		`> = {\n${rows}\n};\n`;

	writeFileSync(OUT, out);
	console.log(
		`wrote ${OUT} (${nations.length} nations, ` +
			`${nations.map((n) => pools.get(n)!.size).join("/")} families)`,
	);
}

main().catch((err: unknown) => {
	console.error(err instanceof Error ? err.message : err);
	process.exit(1);
});
