// Enumerate the family + nation crest PNGs shipped under
// static/sprites/crests/ and emit a TypeScript module the runtime can import
// synchronously. Replaces the hand-maintained KNOWN_FAMILY_CRESTS /
// KNOWN_NATION_CRESTS sets in src/lib/SpriteMap.svelte so adding or removing
// a crest PNG no longer requires editing the component.
//
// Unlike the atlas bakers this isn't a sprite-pack step — there's no image
// processing. It's a directory scan plus a generated TS file. We emit TS
// (not JSON) so SpriteMap can use the data inside $derived blocks without a
// load-state guard.
//
// OUTPUT: src/lib/generated/crests.ts (committed to git)
// SOURCE: static/sprites/crests/CREST_*.png
//
// Run: npm run bake:crests

import { readdir, mkdir, writeFile } from "node:fs/promises";
import { dirname, resolve } from "node:path";
import { fileURLToPath } from "node:url";

const __dirname = dirname(fileURLToPath(import.meta.url));
const CRESTS_DIR = resolve(__dirname, "..", "static", "sprites", "crests");
const OUTPUT_FILE = resolve(
	__dirname,
	"..",
	"src",
	"lib",
	"generated",
	"crests.ts",
);

async function main(): Promise<void> {
	const entries = await readdir(CRESTS_DIR);

	// FAMILY_<NAME> stems, excluding _SEAT variants (which are overlay
	// indicators consumed elsewhere, not crest fallbacks).
	const families = entries
		.filter((f) => f.startsWith("CREST_FAMILY_") && f.endsWith(".png"))
		.map((f) => f.slice("CREST_".length, -".png".length))
		.filter((stem) => !stem.endsWith("_SEAT"))
		.sort();

	// NATION_<STEM> with the NATION_ prefix stripped — the runtime check
	// (resolveNationCrestKey in SpriteMap.svelte) compares against bare
	// stems like "AKSUM".
	const nations = entries
		.filter((f) => f.startsWith("CREST_NATION_") && f.endsWith(".png"))
		.map((f) => f.slice("CREST_NATION_".length, -".png".length))
		.sort();

	const bakedAt = new Date().toISOString();
	const body = renderModule(bakedAt, families, nations);

	await mkdir(dirname(OUTPUT_FILE), { recursive: true });
	await writeFile(OUTPUT_FILE, body);

	console.log(
		`Wrote ${OUTPUT_FILE}\n  families: ${families.length}\n  nations:  ${nations.length}`,
	);
}

function renderModule(
	bakedAt: string,
	families: readonly string[],
	nations: readonly string[],
): string {
	const fmt = (xs: readonly string[]) =>
		xs.map((x) => `\t"${x}",`).join("\n");

	return `// AUTO-GENERATED by scripts/bake-crests.ts. Do not edit.
// Run \`npm run bake:crests\` to refresh from static/sprites/crests/.

export const BAKED_AT = "${bakedAt}";

// FAMILY_<NAME> stems for which a CREST_FAMILY_<NAME>.png ships under
// static/sprites/crests/. Membership gates the per-family crest fallback;
// non-members fall back to the family-class archetype crest.
export const FAMILY_CRESTS: ReadonlySet<string> = new Set([
${fmt(families)}
]);

// Nation stems (NATION_ prefix stripped) for which a CREST_NATION_<STEM>.png
// ships under static/sprites/crests/. Drives the fallback chain in
// resolveNationCrestKey.
export const NATION_CRESTS: ReadonlySet<string> = new Set([
${fmt(nations)}
]);
`;
}

await main();
