// Bake the set of dynasty-unique leader traits from the OW reference XML so
// the challenge scorer can enforce the community's standing rule — "for your
// custom leader, only pick standard traits; no dynasty-unique traits".
//
// A dynasty-unique trait is one the game ties to a historical ruler: its
// trait.xml entry names that ruler in <EncyclopediaCharacter> (TRAIT_HANNIBAL_LEADER
// → CHARACTER_HANNIBAL, TRAIT_CHARIOT_MASTER → CHARACTER_RAMESSES). A standard
// archetype or personality trait has no such link. The set is the whole rule,
// so it is baked rather than hand-listed.
//
// SOURCES (local-only, via the Reference/ resolver — set OLD_WORLD_REFERENCE_DIR
// to an OW install or an XML checkout such as the owtournamentatlas repo):
//   Reference/XML/Infos/trait.xml — <Entry> with <zType>, <EncyclopediaCharacter>
//
// OUTPUT: src/lib/generated/dynasty-traits.ts (frontend) and cloud/src/generated/
// dynasty-traits.ts (Worker) — the wonders dual-emit pattern; the challenge scorer
// and its generated Worker mirror each import their own copy.
//
// Also baked, frontend-only: src/lib/generated/leader-traits.ts — the traits a
// custom leader picks from (the `required_traits` roster in the rules editor):
// the ten <bArchetype> traits, and the <bStrength>/<bWeakness> personality
// traits that are neither dynasty-unique nor <bDisplay> (the scripted ones —
// Famous, Sickly, the Buddhist attainments — that events hand out).
//
// Deterministic — re-running with the same XML is byte-identical.
//
// Run: npm run bake:dynasty-traits

import { readFile, writeFile } from "node:fs/promises";
import { dirname, resolve } from "node:path";
import { fileURLToPath } from "node:url";

import { XMLParser } from "fast-xml-parser";
import { format as prettierFormat, resolveConfig } from "prettier";

import { resolveReferenceXml } from "./lib/paths.js";

const __dirname = dirname(fileURLToPath(import.meta.url));
const REPO_ROOT = resolve(__dirname, "..");
const OUTPUTS = [
	resolve(REPO_ROOT, "src/lib/generated/dynasty-traits.ts"),
	resolve(REPO_ROOT, "cloud/src/generated/dynasty-traits.ts"),
];

interface TraitEntry {
	zType?: string;
	EncyclopediaCharacter?: string;
	bArchetype?: string;
	bStrength?: string;
	bWeakness?: string;
	bDisplay?: string;
}

const LEADER_TRAITS_OUTPUT = resolve(
	REPO_ROOT,
	"src/lib/generated/leader-traits.ts",
);

const parser = new XMLParser({
	ignoreAttributes: true,
	parseTagValue: false,
	ignoreDeclaration: true,
	ignorePiTags: true,
});

async function loadEntries<T>(path: string): Promise<T[]> {
	const xml = await readFile(path, "utf-8");
	const parsed = parser.parse(xml) as { Root?: { Entry?: T | T[] } };
	const entry = parsed.Root?.Entry;
	if (entry == null) return [];
	return Array.isArray(entry) ? entry : [entry];
}

// Emit through Prettier so the committed file matches `npm run format`.
async function formatTs(path: string, source: string): Promise<string> {
	return prettierFormat(source, {
		...(await resolveConfig(path)),
		parser: "typescript",
		filepath: path,
	});
}

async function main(): Promise<void> {
	const infos = resolve(resolveReferenceXml(), "Infos");
	const traits = await loadEntries<TraitEntry>(resolve(infos, "trait.xml"));

	const byTrait: Record<string, string> = {};
	for (const t of traits) {
		if (!t.zType || !t.EncyclopediaCharacter) continue;
		byTrait[t.zType] = t.EncyclopediaCharacter;
	}
	if (Object.keys(byTrait).length === 0) {
		throw new Error(
			"bake-dynasty-traits: trait.xml yielded no <EncyclopediaCharacter> entries",
		);
	}

	const body = Object.keys(byTrait)
		.sort()
		.map((k) => `\t${JSON.stringify(k)}: ${JSON.stringify(byTrait[k])},`)
		.join("\n");

	const out =
		`// AUTO-GENERATED by scripts/bake-dynasty-traits.ts from Reference/XML/Infos\n` +
		`// (trait.xml). Do not edit by hand — re-run \`npm run bake:dynasty-traits\`.\n` +
		`//\n` +
		`// Trait → the historical ruler it belongs to (<EncyclopediaCharacter>).\n` +
		`// A trait in this table is "dynasty-unique" in the challenge rules' sense:\n` +
		`// a custom leader may not pick it. Standard traits are absent.\n` +
		`export const DYNASTY_TRAIT_CHARACTER: Readonly<Record<string, string>> = {\n` +
		`${body}\n};\n\n` +
		`export function isDynastyTrait(trait: string): boolean {\n` +
		`\treturn trait in DYNASTY_TRAIT_CHARACTER;\n` +
		`}\n`;

	for (const out_ of OUTPUTS)
		await writeFile(out_, await formatTs(out_, out), "utf-8");
	console.log(
		`[dynasty-traits] wrote ${Object.keys(byTrait).length} dynasty-unique traits → ${OUTPUTS.map((o) => o.replace(REPO_ROOT + "/", "")).join(", ")}`,
	);

	const pool = {
		archetype: [] as string[],
		strength: [] as string[],
		weakness: [] as string[],
	};
	for (const t of traits) {
		if (!t.zType) continue;
		if (t.bArchetype === "1") pool.archetype.push(t.zType);
		if (t.EncyclopediaCharacter || t.bDisplay === "1") continue;
		if (t.bStrength === "1") pool.strength.push(t.zType);
		if (t.bWeakness === "1") pool.weakness.push(t.zType);
	}
	if (
		pool.archetype.length === 0 ||
		pool.strength.length === 0 ||
		pool.weakness.length === 0
	) {
		throw new Error(
			"bake-dynasty-traits: trait.xml yielded an empty leader-trait pool",
		);
	}
	const list = (xs: string[]) =>
		xs
			.sort()
			.map((x) => `\t\t${JSON.stringify(x)},`)
			.join("\n");
	const leaderOut =
		`// AUTO-GENERATED by scripts/bake-dynasty-traits.ts from Reference/XML/Infos\n` +
		`// (trait.xml). Do not edit by hand — re-run \`npm run bake:dynasty-traits\`.\n` +
		`//\n` +
		`// The traits a custom leader picks from: the archetypes, and the\n` +
		`// strength/weakness personality traits that are neither dynasty-unique nor\n` +
		`// scripted (<bDisplay>). The rules editor's \`required_traits\` roster.\n` +
		`export const LEADER_TRAITS: Readonly<\n` +
		`\tRecord<"archetype" | "strength" | "weakness", readonly string[]>\n` +
		`> = {\n` +
		`\tarchetype: [\n${list(pool.archetype)}\n\t],\n` +
		`\tstrength: [\n${list(pool.strength)}\n\t],\n` +
		`\tweakness: [\n${list(pool.weakness)}\n\t],\n` +
		`};\n`;
	await writeFile(
		LEADER_TRAITS_OUTPUT,
		await formatTs(LEADER_TRAITS_OUTPUT, leaderOut),
		"utf-8",
	);
	console.log(
		`[dynasty-traits] wrote ${pool.archetype.length}/${pool.strength.length}/${pool.weakness.length} archetype/strength/weakness traits → ${LEADER_TRAITS_OUTPUT.replace(REPO_ROOT + "/", "")}`,
	);
}

main().catch((e) => {
	console.error(e);
	process.exit(1);
});
