// Bake THEOLOGY_<zType> → tier from the OW reference XML so a challenge can
// ask for "a state religion with a Tier 2 theology" (a rule the community has
// already used) and the scorer can answer it from a save's theology list.
//
// SOURCES (local-only, via the Reference/ resolver — set OLD_WORLD_REFERENCE_DIR
// to an OW install or an XML checkout such as the owtournamentatlas repo):
//   Reference/XML/Infos/theology.xml — <Entry> with <zType>, <iTier>
//
// The game's <iTier> is 0-based (Mythology/Veneration/Legalism are tier 0);
// players say "Tier 1/2/3", so the table stores the 1-based number they mean.
//
// OUTPUT: src/lib/generated/theology-tiers.ts (frontend) and cloud/src/generated/
// theology-tiers.ts (Worker) — the wonders dual-emit pattern; the challenge scorer
// and its generated Worker mirror each import their own copy.
//
// Deterministic — re-running with the same XML is byte-identical.
//
// Run: npm run bake:theology-tiers

import { readFile, writeFile } from "node:fs/promises";
import { dirname, resolve } from "node:path";
import { fileURLToPath } from "node:url";

import { XMLParser } from "fast-xml-parser";
import { format as prettierFormat, resolveConfig } from "prettier";

import { resolveReferenceXml } from "./lib/paths.js";

const __dirname = dirname(fileURLToPath(import.meta.url));
const REPO_ROOT = resolve(__dirname, "..");
const OUTPUTS = [
	resolve(REPO_ROOT, "src/lib/generated/theology-tiers.ts"),
	resolve(REPO_ROOT, "cloud/src/generated/theology-tiers.ts"),
];

interface TheologyEntry {
	zType?: string;
	iTier?: string;
}

const parser = new XMLParser({
	ignoreAttributes: true,
	parseTagValue: false,
	ignoreDeclaration: true,
	ignorePiTags: true,
});

async function loadEntries<T>(path: string): Promise<T[]> {
	const xml = await readFile(path, "utf-8");
	const parsed = parser.parse(xml) as { Root?: { Entry?: T | T[] } };
	const entry = parsed.Root?.Entry;
	if (entry == null) return [];
	return Array.isArray(entry) ? entry : [entry];
}

// Emit through Prettier so the committed file matches `npm run format`.
async function formatTs(path: string, source: string): Promise<string> {
	return prettierFormat(source, {
		...(await resolveConfig(path)),
		parser: "typescript",
		filepath: path,
	});
}

async function main(): Promise<void> {
	const infos = resolve(resolveReferenceXml(), "Infos");
	const entries = await loadEntries<TheologyEntry>(
		resolve(infos, "theology.xml"),
	);

	const tiers: Record<string, number> = {};
	for (const t of entries) {
		if (!t.zType || !t.zType.startsWith("THEOLOGY_")) continue;
		const tier = t.iTier != null ? Number(t.iTier) : NaN;
		if (!Number.isInteger(tier)) {
			throw new Error(`bake-theology-tiers: ${t.zType} has no integer iTier`);
		}
		tiers[t.zType] = tier + 1;
	}
	if (Object.keys(tiers).length === 0) {
		throw new Error(
			"bake-theology-tiers: theology.xml yielded no THEOLOGY_* entries",
		);
	}

	const body = Object.keys(tiers)
		.sort()
		.map((k) => `\t${JSON.stringify(k)}: ${tiers[k]},`)
		.join("\n");

	const out =
		`// AUTO-GENERATED by scripts/bake-theology-tiers.ts from Reference/XML/Infos\n` +
		`// (theology.xml). Do not edit by hand — re-run \`npm run bake:theology-tiers\`.\n` +
		`//\n` +
		`// Theology → its tier as players say it (1-based; the XML's <iTier> is\n` +
		`// 0-based). Religions establish theologies in tier order.\n` +
		`export const THEOLOGY_TIER: Readonly<Record<string, number>> = {\n` +
		`${body}\n};\n`;

	for (const out_ of OUTPUTS)
		await writeFile(out_, await formatTs(out_, out), "utf-8");
	console.log(
		`[theology-tiers] wrote ${Object.keys(tiers).length} theologies → ${OUTPUTS.map((o) => o.replace(REPO_ROOT + "/", "")).join(", ")}`,
	);
}

main().catch((e) => {
	console.error(e);
	process.exit(1);
});
