// Bake the deep-link encoding tables for owtt — the Old World Tech Tree
// planner at https://alcaras.github.io/owtt/ — so the Techs tab can link each
// player's actual research order into the planner.
//
// owtt's share URLs are positional: `?n=<nation index>&o=<enc,enc,…>` where a
// positive enc is the tech's index in the planner's `techData.techs` array, a
// negative enc is -(index+1) into `techData.bonusTechs`, and `n` indexes
// `window.nationLookup` (see the planner repo's URLPARAM.md). Those arrays are
// the planner's own ordering, not derivable from Reference/XML — so this bake
// fetches the planner's published tech-data.js and snapshots the mapping.
//
// SOURCE (network): https://alcaras.github.io/owtt/tech-data.js
// OUTPUT: src/lib/generated/owtt.ts (checked in, self-contained — no .bake
// sidecar, so bake:finalize never wipes it when this bake hasn't been run).
//
// Run: npm run bake:owtt

import { mkdir, readFile, writeFile } from "node:fs/promises";
import { existsSync } from "node:fs";
import { dirname, resolve } from "node:path";
import { fileURLToPath } from "node:url";

import { format as prettierFormat, resolveConfig } from "prettier";

const __dirname = dirname(fileURLToPath(import.meta.url));
const REPO_ROOT = resolve(__dirname, "..");
const OUTPUT_TS = resolve(REPO_ROOT, "src/lib/generated/owtt.ts");

const OWTT_BASE_URL = "https://alcaras.github.io/owtt/";
const TECH_DATA_URL = `${OWTT_BASE_URL}tech-data.js`;

interface OwttTech {
	id: string;
}
interface OwttWindow {
	gameVersion?: string;
	techData?: { techs?: OwttTech[]; bonusTechs?: OwttTech[] };
	nationLookup?: string[];
}

async function main(): Promise<void> {
	const res = await fetch(TECH_DATA_URL);
	if (!res.ok) {
		throw new Error(`bake-owtt: ${TECH_DATA_URL} → HTTP ${res.status}`);
	}
	const src = await res.text();

	// tech-data.js is a data-only script that assigns onto `window`; run it
	// against a shim to read the arrays exactly as the planner does (regex
	// parsing would silently drift on formatting changes).
	const shim: OwttWindow = {};
	new Function("window", src)(shim);

	const techs = shim.techData?.techs ?? [];
	const bonusTechs = shim.techData?.bonusTechs ?? [];
	const nations = shim.nationLookup ?? [];
	if (techs.length === 0 || nations.length === 0) {
		throw new Error(
			"bake-owtt: tech-data.js parsed to an empty techs/nationLookup — planner format changed?",
		);
	}

	const enc: Record<string, number> = {};
	techs.forEach((t, i) => {
		enc[t.id] = i;
	});
	bonusTechs.forEach((t, i) => {
		// Bonus cards encode as negative: -1 is bonusTechs[0].
		enc[t.id] ??= -(i + 1);
	});

	const nationIndex: Record<string, number> = {};
	nations.forEach((n, i) => {
		nationIndex[n] = i;
	});

	const lines: string[] = [];
	lines.push("// AUTO-GENERATED by scripts/bake-owtt.ts. Do not edit.");
	lines.push("// Run `npm run bake:owtt` to refresh from the live planner.");
	lines.push(`// Source: ${TECH_DATA_URL}`);
	if (shim.gameVersion) {
		lines.push(`// Planner data version: ${shim.gameVersion}`);
	}
	lines.push("");
	lines.push(
		"// Base URL of the owtt tech-tree planner; share links append ?n=&o=.",
	);
	lines.push(
		`export const OWTT_BASE_URL: string = ${JSON.stringify(OWTT_BASE_URL)};`,
	);
	lines.push("");
	lines.push(
		"// TECH_* → planner encoding int: index into the planner's techs array,",
	);
	lines.push("// or -(index+1) into its bonusTechs array for bonus cards.");
	lines.push(
		`export const OWTT_TECH_ENC: Readonly<Record<string, number>> = ${JSON.stringify(enc)};`,
	);
	lines.push("");
	lines.push("// NATION_* → the planner's ?n= nation index.");
	lines.push(
		`export const OWTT_NATION_INDEX: Readonly<Record<string, number>> = ${JSON.stringify(nationIndex)};`,
	);
	lines.push("");

	const config = await resolveConfig(OUTPUT_TS);
	const formatted = await prettierFormat(lines.join("\n"), {
		...config,
		parser: "typescript",
		filepath: OUTPUT_TS,
	});

	await mkdir(dirname(OUTPUT_TS), { recursive: true });
	if (existsSync(OUTPUT_TS)) {
		const existing = await readFile(OUTPUT_TS, "utf-8");
		if (existing === formatted) {
			console.log("bake-owtt: no changes");
			return;
		}
	}
	await writeFile(OUTPUT_TS, formatted);
	console.log(
		`bake-owtt: ${techs.length} techs, ${bonusTechs.length} bonus cards, ${nations.length} nations → ${OUTPUT_TS.replace(REPO_ROOT + "/", "")}`,
	);
}

await main();
