// Bake the Worker's copy of the community atlas' published map pool
// (cloud/src/generated/atlas-pool.ts) from a local owtournamentatlas checkout:
//
//   npx tsx scripts/bake-atlas-pool.ts
//
// The opponent recommender suggests a map for each pair — one whose script
// neither of them has played lately — and does it in the Worker, where the
// pairing is decided. cloud/ is a separate package that can't import from
// src/lib, so the pool it picks from is baked in rather than shared at runtime,
// the same arrangement cloud/src/generated/{law-classes,nation-names,wonders}
// already use.
//
// Only the published pool: those are the duel-tuned configs the community
// actually plays, and the only ones whose anchors resolve on the atlas site, so
// every suggestion can be linked. Reading it is shared with bake-map-caveats
// (scripts/lib/atlas-pool).

import { writeFileSync } from "node:fs";
import { dirname, resolve } from "node:path";
import { fileURLToPath } from "node:url";
import { ATLAS_BASE_URL } from "../src/lib/tournament/map-script-options";
import { readAtlasPool } from "./lib/atlas-pool";

const __dirname = dirname(fileURLToPath(import.meta.url));
const REPO_ROOT = resolve(__dirname, "..");
const OUT = resolve(REPO_ROOT, "cloud/src/generated/atlas-pool.ts");

async function main(): Promise<void> {
	const pool = readAtlasPool();

	const rows = pool
		.map(
			(m) =>
				`\t{\n` +
				`\t\tanchor: ${JSON.stringify(m.anchor)},\n` +
				`\t\tscript: ${JSON.stringify(m.script)},\n` +
				`\t\tname: ${JSON.stringify(m.name)},\n` +
				`\t\tsetting: ${JSON.stringify(m.setting)},\n` +
				`\t},`,
		)
		.join("\n");

	const out =
		`// Generated by scripts/bake-atlas-pool.ts — do not edit by hand.\n` +
		`// Source: owtournamentatlas' published pool (src/pages/index.astro POOL,\n` +
		`// joined to src/data/atlas-dist.json). Re-run when the atlas pool changes.\n\n` +
		`// One map the community plays: what to call it, the script it runs, how\n` +
		`// it is set up, and the anchor that addresses it on the atlas. \`name\`\n` +
		`// carries the variant where the pool holds several of one script ("DOTA\n` +
		`// Jungle"). \`script\` is the raw Old World value — canonicalMapScript()\n` +
		`// in ../tournament/canonical-maps is what makes it comparable with the\n` +
		`// script recorded on a game.\n` +
		`export interface AtlasPoolMap {\n` +
		`\tanchor: string;\n` +
		`\tscript: string;\n` +
		`\tname: string;\n` +
		`\tsetting: string;\n` +
		`}\n\n` +
		`export const ATLAS_POOL: readonly AtlasPoolMap[] = [\n${rows}\n];\n\n` +
		`// Mirrors ATLAS_BASE_URL in src/lib/tournament/map-script-options.ts —\n` +
		`// baked from it rather than retyped, so the two can't drift.\n` +
		`export const ATLAS_BASE_URL = ${JSON.stringify(ATLAS_BASE_URL)};\n`;

	writeFileSync(OUT, out);
	console.log(`wrote ${OUT} (${pool.length} maps)`);
}

main().catch((err: unknown) => {
	console.error(err instanceof Error ? err.message : err);
	process.exit(1);
});
