// Bake each nation's starting techs from the OW reference XML, so the Techs
// tab can tell the three ways a player can come to hold a tech apart.
//
// A save's <TechPathHistory> records the draw every CHOSEN tech was picked
// from. A tech a player holds with no entry there was never drafted — it was
// granted. Two very different things land in that bucket:
//
//   the nation's starting techs  — every Carthage player begins with Trapping,
//                                  Divination and Aristocracy, which says
//                                  nothing about how they played;
//   a genuinely free tech        — a Sages family seat (bRandomTech), an event
//                                  reward, a bonus card.
//
// Without this table the first three rows of every player's list would read as
// free techs, so the interesting case would be buried in noise.
//
// SOURCES (local-only, via the Reference/ symlink resolved by paths.ts):
//   Reference/XML/Infos/nation.xml — <aeStartingTech> on each <Entry>.
//
// OUTPUT: src/lib/generated/starting-techs.ts (checked in, self-contained —
// no .bake sidecar, so bake:finalize never wipes it when this hasn't run).
//
// Run: npm run bake:starting-techs

import { mkdir, readFile, writeFile } from "node:fs/promises";
import { existsSync } from "node:fs";
import { dirname, resolve } from "node:path";
import { fileURLToPath } from "node:url";

import { XMLParser } from "fast-xml-parser";
import { format as prettierFormat, resolveConfig } from "prettier";

import { resolveReferenceXml } from "./lib/paths.js";

const __dirname = dirname(fileURLToPath(import.meta.url));
const REPO_ROOT = resolve(__dirname, "..");
const OUTPUT_TS = resolve(REPO_ROOT, "src/lib/generated/starting-techs.ts");

interface Entry {
	zType?: string;
	aeStartingTech?: { zValue?: string | string[] };
}

const parser = new XMLParser({
	ignoreAttributes: true,
	parseTagValue: false,
	ignoreDeclaration: true,
	ignorePiTags: true,
});

async function main(): Promise<void> {
	const path = resolve(resolveReferenceXml(), "Infos", "nation.xml");
	const parsed = parser.parse(await readFile(path, "utf-8")) as {
		Root?: { Entry?: Entry | Entry[] };
	};
	const entry = parsed.Root?.Entry;
	const nations = entry == null ? [] : Array.isArray(entry) ? entry : [entry];

	const startingTechs: Record<string, string[]> = {};
	for (const nation of nations) {
		if (!nation.zType) continue;
		const raw = nation.aeStartingTech?.zValue;
		const techs = raw == null ? [] : Array.isArray(raw) ? raw : [raw];
		if (techs.length > 0) startingTechs[nation.zType] = techs;
	}
	if (Object.keys(startingTechs).length === 0) {
		throw new Error(
			"bake-starting-techs: nation.xml yielded no <aeStartingTech> — the XML shape changed",
		);
	}

	const sorted = Object.fromEntries(
		Object.keys(startingTechs)
			.sort()
			.map((k) => [k, startingTechs[k]]),
	);
	const lines = [
		"// AUTO-GENERATED by scripts/bake-starting-techs.ts. Do not edit.",
		"// Run `npm run bake:starting-techs` to refresh from Reference/XML.",
		"",
		"// Nation → the techs it begins the game holding (nation.xml",
		"// <aeStartingTech>). A tech a player holds that the save's tech-choice",
		"// history never recorded a draw for was granted rather than drafted;",
		"// this separates 'every Carthage player starts with it' from a free tech",
		"// they actually earned.",
		`export const NATION_STARTING_TECHS: Readonly<Record<string, readonly string[]>> = ${JSON.stringify(sorted)};`,
		"",
	];

	const config = await resolveConfig(OUTPUT_TS);
	const formatted = await prettierFormat(lines.join("\n"), {
		...config,
		parser: "typescript",
		filepath: OUTPUT_TS,
	});
	await mkdir(dirname(OUTPUT_TS), { recursive: true });
	if (existsSync(OUTPUT_TS)) {
		const existing = await readFile(OUTPUT_TS, "utf-8");
		if (existing === formatted) {
			console.log("bake-starting-techs: no changes");
			return;
		}
	}
	await writeFile(OUTPUT_TS, formatted);
	console.log(
		`bake-starting-techs: ${Object.keys(sorted).length} nations → ${OUTPUT_TS.replace(REPO_ROOT + "/", "")}`,
	);
}

await main();
