// Bake the legitimacy cognomen ladder from the OW reference XML — the
// epithets the game awards rulers as their legitimacy accumulates ("the
// Founder" at 10 … "the Great" at 100). The Stats page reuses the ladder as
// its activity tiers: earned honorifics in ascending game order, none of
// them an insult (the negative-legitimacy cognomens are excluded).
//
// SOURCES (local-only, via the Reference/ symlink resolved by paths.ts):
//   Reference/XML/Infos/cognomen.xml — <iLegitimacy> per cognomen.
//   Reference/XML/Infos/text*.xml — TEXT_COGNOMEN_* display strings
//     (the DLC cognomens live in per-DLC text files, e.g. text-eoti.xml).
//
// OUTPUT: src/lib/generated/cognomens.ts (checked in, self-contained).
//
// Run: npm run bake:cognomens

import { mkdir, readdir, readFile, writeFile } from "node:fs/promises";
import { existsSync } from "node:fs";
import { dirname, resolve } from "node:path";
import { fileURLToPath } from "node:url";

import { XMLParser } from "fast-xml-parser";
import { format as prettierFormat, resolveConfig } from "prettier";

import { resolveReferenceXml } from "./lib/paths.js";

const __dirname = dirname(fileURLToPath(import.meta.url));
const REPO_ROOT = resolve(__dirname, "..");
const OUTPUT_TS = resolve(REPO_ROOT, "src/lib/generated/cognomens.ts");

interface Entry {
	zType?: string;
	iLegitimacy?: string;
	"en-US"?: string;
}

const parser = new XMLParser({
	ignoreAttributes: true,
	parseTagValue: false,
	ignoreDeclaration: true,
	ignorePiTags: true,
});

async function loadEntries(path: string): Promise<Entry[]> {
	const xml = await readFile(path, "utf-8");
	const parsed = parser.parse(xml) as { Root?: { Entry?: Entry | Entry[] } };
	const raw = parsed.Root?.Entry;
	return raw == null ? [] : Array.isArray(raw) ? raw : [raw];
}

async function main(): Promise<void> {
	const infosDir = resolve(resolveReferenceXml(), "Infos");
	const textFiles = (await readdir(infosDir)).filter((f) =>
		/^text.*\.xml$/.test(f),
	);
	const [cognomens, ...textSets] = await Promise.all([
		loadEntries(resolve(infosDir, "cognomen.xml")),
		...textFiles.map((f) => loadEntries(resolve(infosDir, f))),
	]);
	const texts = textSets.flat();
	const textByType = new Map(texts.map((t) => [t.zType, t["en-US"]]));

	// COGNOMEN_NEW is the game's epithet for a fresh ruler — it carries no
	// iLegitimacy (it's the starting state, not an award) but it IS the
	// ladder's floor, so it's included at legitimacy 0.
	const ladder = cognomens
		.filter(
			(c) =>
				c.zType &&
				(c.zType === "COGNOMEN_NEW" || Number(c.iLegitimacy ?? 0) > 0),
		)
		.map((c) => {
			// COGNOMEN_GREAT → TEXT_COGNOMEN_GREAT → "the Great". The gendered
			// variants are identical strings in English, so the base form is
			// the display name.
			const name = textByType.get(c.zType!.replace(/^COGNOMEN_/, "TEXT_COGNOMEN_"));
			return {
				type: c.zType!,
				legitimacy: c.iLegitimacy != null ? Number(c.iLegitimacy) : 0,
				name: name ?? null,
			};
		});
	// Every positive-legitimacy cognomen must have display text — a missing
	// string is a parse drift, not an optional field.
	const missing = ladder.filter((c) => c.name == null);
	if (missing.length > 0) {
		throw new Error(
			`bake-cognomens: no display text for ${missing.map((c) => c.type).join(", ")}`,
		);
	}
	if (ladder.length < 20) {
		throw new Error(`bake-cognomens: only ${ladder.length} cognomens parsed`);
	}
	ladder.sort(
		(a, b) => a.legitimacy - b.legitimacy || a.type.localeCompare(b.type),
	);

	const lines: string[] = [];
	lines.push("// AUTO-GENERATED by scripts/bake-cognomens.ts. Do not edit.");
	lines.push("// Run `npm run bake:cognomens` to refresh from Reference/XML.");
	lines.push("");
	lines.push("// The legitimacy cognomen ladder, ascending: the epithets the");
	lines.push("// game awards rulers as legitimacy accumulates (cognomen.xml");
	lines.push("// iLegitimacy > 0, plus the New — the fresh-ruler epithet — at");
	lines.push("// the floor), with their display strings. Fixed name to");
	lines.push('// look up by zType, e.g. COGNOMEN_GREAT → "the Great".');
	lines.push(
		`export const COGNOMEN_LADDER: readonly { readonly type: string; readonly legitimacy: number; readonly name: string }[] = ${JSON.stringify(ladder)};`,
	);
	lines.push("");

	const config = await resolveConfig(OUTPUT_TS);
	const formatted = await prettierFormat(lines.join("\n"), {
		...config,
		parser: "typescript",
		filepath: OUTPUT_TS,
	});
	await mkdir(dirname(OUTPUT_TS), { recursive: true });
	if (existsSync(OUTPUT_TS)) {
		const existing = await readFile(OUTPUT_TS, "utf-8");
		if (existing === formatted) {
			console.log("bake-cognomens: no changes");
			return;
		}
	}
	await writeFile(OUTPUT_TS, formatted);
	console.log(
		`bake-cognomens: ${ladder.length} cognomens → ${OUTPUT_TS.replace(REPO_ROOT + "/", "")}`,
	);
}

await main();
