// Bake the deep-link encoding tables for owtt — the Old World Tech Tree
// planner at https://alcaras.github.io/owtt/ — so the Techs tab can link each
// player's actual research order into the planner.
//
// owtt's share URLs are positional: `?n=<nation index>&o=<enc,enc,…>` where a
// positive enc is the tech's index in the planner's `techData.techs` array, a
// negative enc is -(index+1) into `techData.bonusTechs`, and `n` indexes
// `window.nationLookup` (see the planner repo's URLPARAM.md). Those arrays are
// the planner's own ordering, not derivable from Reference/XML — so this bake
// snapshots the mapping from a LOCAL owtt checkout (resolveOwtt / OWTT_DIR in
// .env), keeping the input diffable and pinnable to a commit rather than
// fetching and executing the live site's JavaScript.
//
// Every emitted tech id is cross-checked against Reference/XML/Infos/tech.xml
// so planner-side drift (renamed/unknown ids) fails the bake loudly. Note the
// positional indices themselves can only change via a re-bake, where the
// generated-file diff makes the change reviewable.
//
// SOURCES (local-only):
//   <owtt>/tech-data.js                — planner data (resolveOwtt)
//   Reference/XML/Infos/tech.xml       — tech id universe for the cross-check
//
// OUTPUT: src/lib/generated/owtt.ts (checked in, self-contained — no .bake
// sidecar, so bake:finalize never wipes it when this bake hasn't been run).
//
// Run: npm run bake:owtt

import { mkdir, readFile, writeFile } from "node:fs/promises";
import { existsSync } from "node:fs";
import { dirname, resolve } from "node:path";
import { fileURLToPath } from "node:url";

import { XMLParser } from "fast-xml-parser";
import { format as prettierFormat, resolveConfig } from "prettier";

import { resolveOwtt, resolveReferenceXml } from "./lib/paths.js";

const __dirname = dirname(fileURLToPath(import.meta.url));
const REPO_ROOT = resolve(__dirname, "..");
const OUTPUT_TS = resolve(REPO_ROOT, "src/lib/generated/owtt.ts");

const OWTT_BASE_URL = "https://alcaras.github.io/owtt/";

interface OwttTech {
	id: string;
}
interface OwttWindow {
	gameVersion?: string;
	techData?: { techs?: OwttTech[]; bonusTechs?: OwttTech[] };
	nationLookup?: string[];
}

async function loadReferenceTechIds(): Promise<Set<string>> {
	const techPath = resolve(resolveReferenceXml(), "Infos", "tech.xml");
	const parser = new XMLParser({
		ignoreAttributes: true,
		parseTagValue: false,
		ignoreDeclaration: true,
		ignorePiTags: true,
	});
	const parsed = parser.parse(await readFile(techPath, "utf-8")) as {
		Root?: { Entry?: { zType?: string } | { zType?: string }[] };
	};
	const entry = parsed.Root?.Entry;
	const entries = entry == null ? [] : Array.isArray(entry) ? entry : [entry];
	return new Set(
		entries
			.map((e) => e.zType)
			.filter((z): z is string => z != null && z.startsWith("TECH_")),
	);
}

async function main(): Promise<void> {
	const techDataPath = resolve(resolveOwtt(), "tech-data.js");
	const src = await readFile(techDataPath, "utf-8");

	// tech-data.js is a data-only script that assigns onto `window`; run it
	// against a shim to read the arrays exactly as the planner does (regex
	// parsing would silently drift on formatting changes). Local checkout
	// only — never remote code.
	const shim: OwttWindow = {};
	new Function("window", src)(shim);

	const techs = shim.techData?.techs ?? [];
	const bonusTechs = shim.techData?.bonusTechs ?? [];
	const nations = shim.nationLookup ?? [];
	if (techs.length === 0 || nations.length === 0) {
		throw new Error(
			"bake-owtt: tech-data.js parsed to an empty techs/nationLookup — planner format changed?",
		);
	}

	// Cross-check the planner's tech ids against the Reference universe so a
	// renamed or unknown id can't silently poison the checked-in table.
	const referenceTechIds = await loadReferenceTechIds();
	const unknown = [...techs, ...bonusTechs]
		.map((t) => t.id)
		.filter((id) => !referenceTechIds.has(id));
	if (unknown.length > 0) {
		throw new Error(
			`bake-owtt: ${unknown.length} planner tech id(s) not in Reference/XML tech.xml: ${unknown.join(", ")}`,
		);
	}

	const enc: Record<string, number> = {};
	techs.forEach((t, i) => {
		enc[t.id] = i;
	});
	bonusTechs.forEach((t, i) => {
		// Bonus cards encode as negative: -1 is bonusTechs[0].
		enc[t.id] ??= -(i + 1);
	});

	const nationIndex: Record<string, number> = {};
	nations.forEach((n, i) => {
		nationIndex[n] = i;
	});

	const lines: string[] = [];
	lines.push("// AUTO-GENERATED by scripts/bake-owtt.ts. Do not edit.");
	lines.push(
		"// Run `npm run bake:owtt` to refresh from a local owtt checkout (OWTT_DIR).",
	);
	if (shim.gameVersion) {
		lines.push(`// Planner data version: ${shim.gameVersion}`);
	}
	lines.push("");
	lines.push(
		"// Base URL of the owtt tech-tree planner; share links append ?n=&o=.",
	);
	lines.push(
		`export const OWTT_BASE_URL: string = ${JSON.stringify(OWTT_BASE_URL)};`,
	);
	lines.push("");
	lines.push(
		"// TECH_* → planner encoding int: index into the planner's techs array,",
	);
	lines.push("// or -(index+1) into its bonusTechs array for bonus cards.");
	lines.push(
		`export const OWTT_TECH_ENC: Readonly<Record<string, number>> = ${JSON.stringify(enc)};`,
	);
	lines.push("");
	lines.push("// NATION_* → the planner's ?n= nation index.");
	lines.push(
		`export const OWTT_NATION_INDEX: Readonly<Record<string, number>> = ${JSON.stringify(nationIndex)};`,
	);
	lines.push("");

	const config = await resolveConfig(OUTPUT_TS);
	const formatted = await prettierFormat(lines.join("\n"), {
		...config,
		parser: "typescript",
		filepath: OUTPUT_TS,
	});

	await mkdir(dirname(OUTPUT_TS), { recursive: true });
	if (existsSync(OUTPUT_TS)) {
		const existing = await readFile(OUTPUT_TS, "utf-8");
		if (existing === formatted) {
			console.log("bake-owtt: no changes");
			return;
		}
	}
	await writeFile(OUTPUT_TS, formatted);
	console.log(
		`bake-owtt: ${techs.length} techs, ${bonusTechs.length} bonus cards, ${nations.length} nations → ${OUTPUT_TS.replace(REPO_ROOT + "/", "")}`,
	);
}

await main();
