// Bake the atlas map-caveat table (src/lib/generated/map-caveats.ts) from a
// local owtournamentatlas checkout:
//
//   npx tsx scripts/bake-map-caveats.ts
//
// For every map in the atlas' published pool it records the minimum city-site
// count observed across that config's generations, keyed by the map's atlas URL
// anchor. The frontend uses the table two ways: `mapInAtlas` (a map is linkable
// iff its anchor is a key here) and the "can spawn with 10 or fewer city sites"
// caveat in the admin scheduling DM (mapCaveatNote).
//
// Reading the pool — parsing it out of the atlas' index.astro, computing each
// config's anchor, resolving its map script — lives in scripts/lib/atlas-pool,
// shared with bake-atlas-pool, which bakes the Worker's copy of the same pool.

import { writeFileSync } from "node:fs";
import { dirname, resolve } from "node:path";
import { fileURLToPath } from "node:url";
import { readAtlasPool } from "./lib/atlas-pool";

// Single source of the low-city-sites threshold emitted into the generated
// table (the runtime reads it back from there via mapCaveatNote).
const LOW_CITY_SITES_THRESHOLD = 10;

const __dirname = dirname(fileURLToPath(import.meta.url));
const REPO_ROOT = resolve(__dirname, "..");
const OUT = resolve(REPO_ROOT, "src/lib/generated/map-caveats.ts");

async function main(): Promise<void> {
	const pool = readAtlasPool();

	const body = pool
		.map((r) => `\t${JSON.stringify(r.anchor)}: ${r.minSites},`)
		.join("\n");
	const out =
		`// Generated by scripts/bake-map-caveats.ts — do not edit by hand.\n` +
		`// Source: owtournamentatlas src/data/atlas-dist.json (dist.sites.min per\n` +
		`// published pool config), keyed by the map's atlas URL anchor (the same\n` +
		`// slug atlasAnchor() in $lib/tournament/map-script-options produces).\n` +
		`// Re-run when the atlas pool or its generation stats change.\n\n` +
		`// Minimum city sites observed across a map's generations. A map "can\n` +
		`// sometimes spawn with ${LOW_CITY_SITES_THRESHOLD} or fewer city sites" when its minimum is at or\n` +
		`// below LOW_CITY_SITES_THRESHOLD — surfaced in the admin scheduling DM so\n` +
		`// players know a low-site roll may be rerolled. Maps absent here are not\n` +
		`// in the atlas (no caveat, no link).\n` +
		`export const MAP_MIN_CITY_SITES: Record<string, number> = {\n${body}\n};\n\n` +
		`// A map can spawn few city sites when its observed minimum is at or below\n` +
		`// this.\n` +
		`export const LOW_CITY_SITES_THRESHOLD = ${LOW_CITY_SITES_THRESHOLD};\n`;

	writeFileSync(OUT, out);
	console.log(`wrote ${OUT} (${pool.length} maps)`);
}

main().catch((err: unknown) => {
	console.error(err instanceof Error ? err.message : err);
	process.exit(1);
});
