// Bake the military-power comparison tiers from the OW reference XML, so the
// Military tab can classify a player's standing vs the opponent exactly the
// way the game does.
//
// SOURCES (local-only, via the Reference/ symlink resolved by paths.ts):
//   Reference/XML/Infos/power.xml — each tier's <iPercent> upper bound.
//
// The game's classification is InfoHelpers.getStrength → getBestPercentValue:
// percent = theirValue × 100 / ourValue (integer division), and the tier with
// the smallest threshold ≥ that percent wins. The entry with no <iPercent>
// (Much Stronger) is the catch-all — InfoPercentBase defaults miPercent to
// int.MaxValue. Both sides feed Player.calculateTotalStrength(), which is
// exactly the value the save records per turn as MilitaryPowerHistory
// (Player.cs:16952), i.e. the blob's military_power series.
//
// OUTPUT: src/lib/generated/power-tiers.ts (checked in, self-contained).
//
// Run: npm run bake:power-tiers

import { mkdir, readFile, writeFile } from "node:fs/promises";
import { existsSync } from "node:fs";
import { dirname, resolve } from "node:path";
import { fileURLToPath } from "node:url";

import { XMLParser } from "fast-xml-parser";
import { format as prettierFormat, resolveConfig } from "prettier";

import { resolveReferenceXml } from "./lib/paths.js";

const __dirname = dirname(fileURLToPath(import.meta.url));
const REPO_ROOT = resolve(__dirname, "..");
const OUTPUT_TS = resolve(REPO_ROOT, "src/lib/generated/power-tiers.ts");

interface Entry {
	zType?: string;
	iPercent?: string;
}

async function main(): Promise<void> {
	const xml = await readFile(
		resolve(resolveReferenceXml(), "Infos", "power.xml"),
		"utf-8",
	);
	const parsed = new XMLParser({
		ignoreAttributes: true,
		parseTagValue: false,
		ignoreDeclaration: true,
		ignorePiTags: true,
	}).parse(xml) as { Root?: { Entry?: Entry | Entry[] } };
	const raw = parsed.Root?.Entry;
	const entries = raw == null ? [] : Array.isArray(raw) ? raw : [raw];

	const tiers = entries
		.filter((e) => e.zType)
		.map((e) => ({
			type: e.zType!,
			percent: e.iPercent != null ? Number(e.iPercent) : null,
		}));
	// A renamed tag would silently produce an empty or capless table and
	// misclassify every game — fail the bake instead.
	if (tiers.length < 3) {
		throw new Error(`bake-power-tiers: only ${tiers.length} tiers parsed`);
	}
	if (tiers.filter((t) => t.percent == null).length !== 1) {
		throw new Error("bake-power-tiers: expected exactly one catch-all tier");
	}

	const lines: string[] = [];
	lines.push("// AUTO-GENERATED by scripts/bake-power-tiers.ts. Do not edit.");
	lines.push("// Run `npm run bake:power-tiers` to refresh from Reference/XML.");
	lines.push("");
	lines.push("// power.xml in file order. A player's military standing vs an");
	lines.push("// opponent is bucketed by percent = theirPower × 100 / ourPower");
	lines.push("// (integer division): the tier with the smallest percent ≥ that");
	lines.push("// value wins (InfoHelpers.getBestPercentValue); `percent: null`");
	lines.push("// (Much Stronger) is the catch-all — InfoPercentBase defaults to");
	lines.push("// int.MaxValue. Both sides are Player.calculateTotalStrength(),");
	lines.push("// the value the save records as MilitaryPowerHistory.");
	lines.push(
		`export const POWER_TIERS: readonly { readonly type: string; readonly percent: number | null }[] = ${JSON.stringify(tiers)};`,
	);
	lines.push("");

	const config = await resolveConfig(OUTPUT_TS);
	const formatted = await prettierFormat(lines.join("\n"), {
		...config,
		parser: "typescript",
		filepath: OUTPUT_TS,
	});
	await mkdir(dirname(OUTPUT_TS), { recursive: true });
	if (existsSync(OUTPUT_TS)) {
		const existing = await readFile(OUTPUT_TS, "utf-8");
		if (existing === formatted) {
			console.log("bake-power-tiers: no changes");
			return;
		}
	}
	await writeFile(OUTPUT_TS, formatted);
	console.log(
		`bake-power-tiers: ${tiers.length} tiers → ${OUTPUT_TS.replace(REPO_ROOT + "/", "")}`,
	);
}

await main();
