// Bake the UNIT_<zType> → { strength, tech, naval } table from the OW reference
// XML (Infos/unit.xml). Powers the Military tab's "milpower built" figure
// (milpower per unit = displayed strength × 10 = the XML's <iStrength>) and the
// unit-tech-unlock markers in the event rail.
//
// SOURCE (local-only, via the Reference/ resolver — set OLD_WORLD_REFERENCE_DIR
// to an OW install or an XML checkout such as the owtournamentatlas repo):
//   Reference/XML/Infos/unit.xml — <Entry> with <zType>, <iStrength>,
//                                   <TechPrereq>, <zAudioMovementType>
//
// Output: src/lib/generated/unit-stats.ts (committed; regenerate on Reference
// refresh). Deterministic — re-running with the same XML is byte-identical.

import { readFile, writeFile } from "node:fs/promises";
import { dirname, resolve } from "node:path";
import { fileURLToPath } from "node:url";

import { XMLParser } from "fast-xml-parser";

import { resolveReferenceXml } from "./lib/paths.js";

const __dirname = dirname(fileURLToPath(import.meta.url));
const REPO_ROOT = resolve(__dirname, "..");
const OUT = resolve(REPO_ROOT, "src/lib/generated/unit-stats.ts");

interface UnitEntry {
	zType?: string;
	iStrength?: string;
	TechPrereq?: string;
	zAudioMovementType?: string;
}

const parser = new XMLParser({
	ignoreAttributes: true,
	parseTagValue: false,
	ignoreDeclaration: true,
	ignorePiTags: true,
});

async function loadEntries(path: string): Promise<UnitEntry[]> {
	const xml = await readFile(path, "utf-8");
	const parsed = parser.parse(xml) as { Root?: { Entry?: UnitEntry | UnitEntry[] } };
	const entry = parsed.Root?.Entry;
	if (entry == null) return [];
	return Array.isArray(entry) ? entry : [entry];
}

async function main(): Promise<void> {
	const unitPath = resolve(resolveReferenceXml(), "Infos", "unit.xml");
	const entries = await loadEntries(unitPath);

	const stats: Record<
		string,
		{ strength: number; tech: string | null; naval: boolean }
	> = {};
	for (const u of entries) {
		const zType = u.zType;
		if (!zType || !zType.startsWith("UNIT_")) continue;
		const iStrength = u.iStrength != null ? Number(u.iStrength) : NaN;
		if (!Number.isFinite(iStrength) || iStrength <= 0) continue; // non-combat
		stats[zType] = {
			// Displayed strength = <iStrength> / 10 (milpower = strength × 10).
			strength: iStrength / 10,
			tech: u.TechPrereq ?? null,
			naval: u.zAudioMovementType === "NAVAL",
		};
	}

	const keys = Object.keys(stats).sort();
	const body = keys
		.map((k) => {
			const s = stats[k];
			const tech = s.tech == null ? "null" : JSON.stringify(s.tech);
			return `\t${JSON.stringify(k)}: { strength: ${s.strength}, tech: ${tech}, naval: ${s.naval} },`;
		})
		.join("\n");

	const out =
		`// AUTO-GENERATED by scripts/bake-unit-stats.ts from Reference/XML/Infos/unit.xml.\n` +
		`// Do not edit by hand — re-run \`npm run bake:unit-stats\`.\n` +
		`//\n` +
		`// strength = displayed unit strength (military power per unit = strength × 10).\n` +
		`// tech = the unit's unlocking tech (TechPrereq), or null. naval = sea unit.\n\n` +
		`export interface UnitStat {\n` +
		`\tstrength: number;\n` +
		`\ttech: string | null;\n` +
		`\tnaval: boolean;\n` +
		`}\n\n` +
		`export const UNIT_STATS: Readonly<Record<string, UnitStat>> = {\n` +
		`${body}\n};\n`;

	await writeFile(OUT, out, "utf-8");
	console.log(`[unit-stats] wrote ${keys.length} units → ${OUT}`);
}

main().catch((e) => {
	console.error(e);
	process.exit(1);
});
