// The intentional delta between the frontend challenge scorer and its Worker
// mirror, expressed as a pure transform: scripts/bake-challenge-mirror.ts
// writes the mirror through it, and cloud/src/challenges/mirror.test.ts
// re-runs it to assert the on-disk files are exactly what the transform
// produces — the momentum-mirror pattern, for the two modules the scorer is.
//
// The delta is the header only. The scorer's imports are all relative and
// resolve to the same paths from cloud/src/challenges/ as from
// src/lib/challenges/ (`../generated/*` → the dual-emitted Worker tables,
// `./types` → the mirrored types), so nothing is rewritten; the guard below
// is what keeps it that way — a `$lib` alias or a parser import would break
// the Worker bundle, and it fails here instead of at deploy.
//
// Deliberately import-free: the test runs under the worker tsconfig, which
// ships no Node types.

export const CHALLENGE_MIRRORS = ["scoring", "types"] as const;

// The generated modules the scorer may import — each is dual-emitted to
// cloud/src/generated/ by its bake, so the mirror's copy of the import
// resolves. Anything else is a bundle break.
const ALLOWED_IMPORTS = new Set([
	"../generated/dynasty-traits",
	"../generated/theology-tiers",
	"../generated/unit-stats",
	"../generated/wonders",
	"./types",
]);

const IMPORT_RE = /^(?:import|export)[^"']*from\s+["']([^"']+)["']/gm;

function mirrorHeader(name: string): string {
	return [
		"// AUTO-GENERATED by scripts/bake-challenge-mirror.ts — do not edit.",
		"// THIS IS THE MIRROR — the source of truth is",
		`// src/lib/challenges/${name}.ts; edit that file and run`,
		"// `npm run bake:challenge-mirror`.",
		"",
		"",
	].join("\n");
}

export function mirrorChallengeSource(name: string, front: string): string {
	for (const m of front.matchAll(IMPORT_RE)) {
		const spec = m[1];
		if (!ALLOWED_IMPORTS.has(spec)) {
			throw new Error(
				`challenge-mirror: src/lib/challenges/${name}.ts imports "${spec}", which the Worker mirror cannot resolve — keep the scorer to ./types and the dual-emitted ../generated/* tables`,
			);
		}
	}
	return mirrorHeader(name) + front;
}
