// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { FileImportError } from "./FileImportError";

export type BatchImportResult = { total_files: number, successful: number, failed: number, skipped: number, errors: Array<FileImportError>, duration_ms: number, };
