// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * City information for the Cities tab
 */
export type CityInfo = { city_id: number, city_name: string, owner_nation: string | null, family: string | null, 
/**
 * Family class enum (FAMILYCLASS_CHAMPIONS, FAMILYCLASS_LANDOWNERS, ...).
 * Frontend uses this as the crest fallback when the per-family crest art
 * isn't in our shipped sprite set — every class has a CREST_ARCHETYPE_X
 * sprite available, but only a small subset of families do.
 */
family_class: string | null, founded_turn: number, is_capital: boolean, citizens: number, governor_name: string | null, 
/**
 * Culture level as string enum (CULTURE_WEAK, CULTURE_DEVELOPING, CULTURE_STRONG, CULTURE_ESTABLISHED, CULTURE_LEGENDARY)
 */
culture_level: string | null, growth_count: number, unit_production_count: number, specialist_count: number, buy_tile_count: number, hurry_civics_count: number, hurry_money_count: number, hurry_training_count: number, hurry_population_count: number, };
