// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { PlayerInfo } from "./PlayerInfo";

export type GameDetails = { match_id: number, game_name: string | null, save_date: string | null, total_turns: number, map_size: string | null, map_width: number | null, map_height: number | null, map_class: string | null, game_mode: string | null, opponent_level: string | null, difficulty: string | null, victory_conditions: string | null, enabled_mods: string | null, enabled_dlc: string | null, winner_player_id: number | null, winner_name: string | null, winner_civilization: string | null, winner_victory_type: string | null, players: Array<PlayerInfo>, };
