// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { PlayerInfo } from "./PlayerInfo";

export type GameDetails = { match_id: number, game_name: string | null, save_date: string | null, total_turns: number, map_size: string | null, map_width: number | null, map_height: number | null, game_mode: string | null, opponent_level: string | null, players: Array<PlayerInfo>, };
