// Originally generated by ts-rs from the (now-removed) Rust desktop port.
// Frozen as a hand-maintained TS type since the Rust source is gone.
import type { PlayerInfo } from "./PlayerInfo";

export type GameDetails = {
	match_id: number;
	game_name: string | null;
	save_date: string | null;
	total_turns: number;
	map_size: string | null;
	map_width: number | null;
	map_height: number | null;
	map_class: string | null;
	map_aspect_ratio: string | null;
	map_options: Record<string, string | boolean> | null;
	// Set game-wide option flags, `zType → true`. PARENT options only — a
	// sub-option is never written to the save, so testing for one reads false
	// even when it's in force (see the parser's parseGameOptions). Added in
	// PARSER_VERSION 2.11.0; null/absent on older blobs, which means "unknown",
	// NOT "no options set".
	game_options: Record<string, true> | null;
	game_mode: string | null;
	opponent_level: string | null;
	difficulty: string | null;
	victory_conditions: string | null;
	enabled_mods: string | null;
	enabled_dlc: string | null;
	winner_player_id: number | null;
	winner_name: string | null;
	winner_civilization: string | null;
	winner_victory_type: string | null;
	players: Array<PlayerInfo>;
};
