// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Religion founded in a game, with founder nation and founding turn
 */
export type GameReligion = { religion_name: string, founded_turn: number | null, founder_nation: string | null,
/**
 * xml_id of the founding player (Player.xmlId). Distinguishes same-nation
 * founders in mirror matches, where founder_nation collides. Optional:
 * absent on blobs parsed before PARSER_VERSION 2.6.0.
 */
founder_player_xml_id?: number | null,
/**
 * Theologies the religion established (THEOLOGY_X enums, from the save's
 * ReligionTheology list). Optional: absent on blobs before PARSER_VERSION
 * 2.15.0.
 */
theologies?: Array<string>, };
