// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type GameInfo = { match_id: number, game_name: string | null, save_date: string | null, turn_year: number | null, human_nation: string | null, total_turns: number | null, human_won: boolean | null, };
