// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { NationStats } from "./NationStats";

export type GameStatistics = { total_games: number, nations: Array<NationStats>, };
