// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Religion founded in a game, with founder nation and founding turn
 */
export type GameReligion = { religion_name: string, founded_turn: number | null, founder_nation: string | null, };
