// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ImportResult } from "./ImportResult";

export type ImportProgress = { 
/**
 * Number of files processed so far
 */
current: number, 
/**
 * Total number of files to import
 */
total: number, 
/**
 * Name of the file currently being processed
 */
current_file: string, 
/**
 * Milliseconds elapsed since import started
 */
elapsed_ms: number, 
/**
 * Estimated milliseconds remaining
 */
estimated_remaining_ms: number, 
/**
 * Import speed in files per second
 */
speed: number, 
/**
 * Result of the current file import (if completed)
 */
result: ImportResult | null, };
