// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Import result
 */
export type ImportResult = { success: boolean, match_id: number, game_id: string, is_new: boolean, error: string | null, };
