// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Single improvement with its city and owner information
 */
export type ImprovementInfo = { nation: string | null,
/**
 * xml_id of the owning player (Player.xmlId). Distinguishes same-nation
 * owners in mirror matches, where nation collides. Optional: absent on
 * blobs parsed before PARSER_VERSION 2.6.0.
 */
owner_player_xml_id?: number | null, city_name: string | null,
/**
 * xml_id of the city whose territory the tile sits in. Optional: absent on
 * blobs parsed before PARSER_VERSION 2.20.0.
 */
city_xml_id?: number | null,
improvement: string,
/**
 * The specialist the GAME reads off this tile — `Tile.getSpecialist`: the one
 * the save recorded, or the free one a neighbouring improvement gives the tile
 * when none is stored. `Tile.writeGameXML` guards `<Specialist>` on the STORED
 * value, so the save holds nothing for a free one and the parser derives it
 * from adjacency (see derive/free-specialists.ts). Blobs parsed before
 * PARSER_VERSION 2.21.0 carry only the stored kind.
 */
specialist: string | null, resource: string | null,
/**
 * Turns of construction still to go, or null once the improvement stands
 * (the tile's <ImprovementBuildTurnsLeft>). A tile carries its improvement
 * from the turn work starts, so without this a half-built wonder counts as
 * built. Optional: absent on blobs parsed before PARSER_VERSION 2.20.0.
 */
build_turns_left?: number | null, };
