// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ImprovementInfo } from "./ImprovementInfo";

/**
 * Response for get_improvement_data command
 */
export type ImprovementData = { improvements: Array<ImprovementInfo>, };
