// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type KnownOnlineId = { online_id: string, player_names: Array<string>, save_count: number, };
