// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { LawAdoptionDataPoint } from "./LawAdoptionDataPoint";

export type LawAdoptionHistory = { player_id: number, player_name: string, nation: string | null, data: Array<LawAdoptionDataPoint>, };
