// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ReligionInfo } from "./ReligionInfo";

/**
 * Tile data for map visualization
 */
export type MapTile = { x: number, y: number, terrain: string | null, height: string | null, vegetation: string | null, resource: string | null, improvement: string | null, improvement_pillaged: boolean, 
/**
 * Turns of construction still owed on `improvement`; null once built.
 * `> 0` is the game's `isImprovementUnfinished()`, which `getActiveImprovement`
 * treats exactly like pillage — the improvement neither pays its own yields
 * nor grants adjacency bonuses. Optional: absent on blobs parsed before
 * PARSER_VERSION 2.17.0.
 */
improvement_turns_left?: number | null, has_road: boolean, specialist: string | null,
/**
 * True when `specialist` is the free specialist a neighbouring improvement
 * gives this tile rather than one the save recorded. It is an ordinary
 * specialist in the game either way: `Tile.getSpecialist` returns the free one
 * when none is stored, but `Tile.writeGameXML` guards `<Specialist>` on the
 * STORED value, so the save holds nothing for it and the parser derives it
 * from adjacency instead (see derive/free-specialists.ts). Absent on blobs
 * parsed before PARSER_VERSION 2.21.0, which carry only stored specialists —
 * so `?? false` reads correctly on every blob.
 */
specialist_free?: boolean, tribe_site: string | null, 
/**
 * All religions present in this tile's city (up to 5)
 */
religions: Array<ReligionInfo>, river_w: boolean, river_sw: boolean, river_se: boolean, 
/**
 * Resolved from owner_player_id -> players.nation
 */
owner_nation: string | null,
/**
 * xml_id of the player owning this tile at the represented turn (the
 * companion to owner_nation, which loses the player in same-nation mirror
 * matches). Drives per-turn resolution of a city's ruling family on the map.
 * Optional: absent on blobs parsed before PARSER_VERSION 2.10.0.
 */
owner_player_xml_id?: number | null,
/**
 * Resolved from owner_city_id -> cities.city_name
 */
owner_city: string | null,
/**
 * True if this tile is a city center
 */
is_city_center: boolean, 
/**
 * True if this tile is a capital city center
 */
is_capital: boolean, };
