// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type MatchDebugRow = { match_id: number, game_id: string, game_name: string | null, file_name: string, };
