// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type NationDynastyRow = { nation: string | null, dynasty: string | null, count: number, };
