// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type PlayerHistoryPoint = { turn: number, points: number | null, military_power: number | null, legitimacy: number | null, };
