// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Unit production data for the Military tab
 */
export type PlayerUnitProduced = { player_id: number, player_name: string, nation: string | null, unit_type: string, count: number, };
