// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { PlayerHistoryPoint } from "./PlayerHistoryPoint";

export type PlayerHistory = { player_id: number, player_name: string, history: Array<PlayerHistoryPoint>, };
