// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Tauri command to get detailed player data per match for debugging
 *
 * Returns match_id, nation, and dynasty for all players
 */
export type PlayerDebugRow = { match_id: number, player_name: string, nation: string | null, dynasty: string | null, is_human: boolean, };
