// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A single completed tech entry for a player
 */
export type PlayerTech = { player_id: number, player_name: string, nation: string | null, tech: string, completed_turn: number, };
