// Originally generated by ts-rs from the (now-removed) Rust desktop port.
// Frozen as a hand-maintained TS type since the Rust source is gone.

export type PlayerInfo = {
	player_name: string;
	nation: string | null;
	is_human: boolean;
	legitimacy: number | null;
	state_religion: string | null;
	difficulty: string | null;
};
