// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A single law entry for a player
 */
export type PlayerLaw = { player_id: number, player_name: string, nation: string | null, law_category: string, law: string, adopted_turn: number, change_count: number, };
