// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A completed wonder for a player
 */
export type PlayerWonder = { player_id: number, player_name: string, nation: string | null, wonder: string, completed_turn: number, };
