// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type PlayerInfo = { player_name: string, nation: string | null, is_human: boolean, legitimacy: number | null, state_religion: string | null, };
