// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Religion info with founder nation for map visualization
 */
export type ReligionInfo = { religion_name: string, founder_nation: string | null, };
