// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A single save date entry for the calendar chart
 */
export type SaveDateEntry = { 
/**
 * Date in YYYY-MM-DD format
 */
date: string, 
/**
 * Nation the save owner played as (e.g., "NATION_ROME")
 */
nation: string | null, };
