// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Share info returned to the frontend. Does NOT include delete_token.
 */
export type ShareInfo = { share_id: string, share_url: string, shared_at: string, };
