// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A single data point in a tech discovery timeline
 */
export type TechDiscoveryDataPoint = { turn: number, tech_count: number, 
/**
 * The name of the tech discovered at this point (None for synthetic start/end points)
 */
tech_name: string | null, };
