// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { TechDiscoveryDataPoint } from "./TechDiscoveryDataPoint";

/**
 * Tech discovery history for a player
 */
export type TechDiscoveryHistory = { player_id: number, player_name: string, nation: string | null, data: Array<TechDiscoveryDataPoint>, };
