// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type YieldDataPoint = { turn: number, 
/**
 * Display value (already converted from fixed-point by dividing by 10)
 */
amount: number | null, };
