// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type YieldDataPoint = { turn: number, 
/**
 * Per-turn production rate (from yield_history, divided by 10)
 */
rate: number | null, 
/**
 * Cumulative total (from yield_total_history or computed running sum, divided by 10)
 */
cumulative: number | null, };
